### ISSUE TITLE
Tests fail locally with SQLITE_ERROR error

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#102]
Although the [CI is green](https://travis-ci.org/Midburn/Spark/builds/198922697), when I run tests locally one of them fails:

> npm test
> 
> > spark@1.1.0 test C:\work\Midburn\Spark
> > mocha  "routes/*test.js"
> 
> 07/02/17 12:07:06.473 INFO ..\..\..\app.js : Spark is starting...
> 07/02/17 12:07:07.089 INFO ..\..\..\app.js : Spark environment: NODE_ENV =
> 07/02/17 12:07:07.090 INFO ..\..\..\app.js : --- Spark is running :) ---
> 
> 
>   Main routes
> 07/02/17 12:07:07.164 INFO ..\..\..\app.js : GET / 302 8.267 ms - 35
>     √ responds to / with redirect to hebrew
> 07/02/17 12:07:07.521 INFO ..\..\..\app.js : GET /he/login 200 346.460 ms - 4302
>     √ greets in Hebrew (353ms)
> 07/02/17 12:07:07.586 INFO ..\..\..\app.js : GET /en/login 200 58.080 ms - 3979
>     √ greets in English (62ms)
> 07/02/17 12:07:07.642 INFO ..\..\..\app.js : GET /he/signup 200 53.213 ms - 4996
>     √ shows signup form in Hebrew (56ms)
> 07/02/17 12:07:07.686 INFO ..\..\..\app.js : GET /en/signup 200 40.083 ms - 4691
>     √ shows signup form in English (43ms)
> 07/02/17 12:07:07.713 INFO ..\..\..\app.js : GET /foo/bar 404 22.779 ms - 9713
>     √ returns 404 MOOP! on everything else
> 07/02/17 12:07:07.717 INFO ..\..\..\app.js : GET /auth/facebook 302 1.512 ms - 0
>     √ redirects to facebook on facebok login
> 07/02/17 12:07:07.737 ERROR ..\..\..\app.js : Possibly Unhandled Rejection at: Promise  Promise {
>   <rejected> { Error: delete from "users" where "email" = 'main_routes_test@localhost' - SQLITE_ERROR: no such table: users
>     at Error (native) errno: 1, code: 'SQLITE_ERROR' } }
>     1) logs-in a drupal user
> 
> 
>   7 passing (3s)
>   1 failing
> 
>   1) Main routes logs-in a drupal user:
>      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
> 
> 
> 
> 
> npm ERR! Test failed.  See above for more details.

**Comment by netanelben** [comment]
Forgot to ``knex migrate:latest`` mybe?

**Comment by ripper234** [comment]
Local tests should not be reliant on knex migrations - they run on SQLite which is cleared on every `npm test` run.

**Comment by ripper234** [comment]
So, it appears the `npm test` script wasn't Windows-friendly.
Fixed in #226 (merge pending).
