### ISSUE TITLE
Language selector in header is not working

### ISSUE THREAD

**Issue by roy-zahor** [Midburn/spark#106]
Small UI bug. It used to work before (can't remember exactley when)

### Description

The language selector on the header is not working.

### Steps to Reproduce

-> login to the system 
-> enter any page
-> click the language selector icon in the header (the flag) 
-> not working.

### Expected behavior

See above

### Actual behavior

See above

**Comment by netanelben** [comment]
@roy-zahor, I tested it here, works fine from mobile chrome
http://54.194.247.12/en/home

**Comment by OriHoch** [comment]
I don't see the original bug, but there is a problem in the npo page:

#### reproduction steps
* login
* click on "npo" link in header
* change the language

##### expected
* go to npo page in chosen language

##### actual
* goes to login page

**Comment by natekonimbo** [comment]
Fixed.
