### ISSUE TITLE
Auto deploy fails

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#113]
### Overview of the problem

Tried `/spark-deploy v1.3.2`

My username appears in .env file.

### Expected behavior
Deploy latest release.

### Actual behavior
Received permission denied.

**Comment by OriHoch** [comment]
I couldn't find a specific problem, but I added some logs so if you try again I might be able to debug

What is the specific error you are getting? Please add a screenshot from slack

You can also deploy from ssh, for example:
```
$ /opt/spark/deploy.sh v1.3.2
```

**Comment by OriHoch** [comment]
@natekonimbo  - is the problem fixed? everything is working well for you now?
