### ISSUE TITLE
Insert data (staging/production)

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#114]
### Spark Users

the following data set contains spark users with role: camp_manager

table: `users`
[data set](https://slack-files.com/T0JMLJX7H-F48FFMBQX-4b20dc042c)

#### Sub-tasks (important)
1. create a relation user-camp identified by `email`
2. ~generate password for each user & insert to table~ (ON-HOLD)

### 2. Spark Camps

data set includes camps, with details -- all in the same table

table: `camps`
[data set](https://slack-files.com/T0JMLJX7H-F47QKT9PU-0fcddfa4c5)

**Comment by OriHoch** [comment]
please be more specific regarding how you would like the data to be imported

* *users*
    * csv file has fields fullName, phone, email
    * DB table has:
        * first_name / last_name / name - seems we are only using first_name and last_name in spark registrtaion.
        * regarding phone - DB has fields cell_phone and extra_phone. 
        * there are also other fields which need to decide what value to put in for them - validated / enabled  / reset_password_(token|expired) / email_validation_(token|expired) / roles

* *camps*
    * csv file has fields phone / email / fullName - which don't exist in DB camps table
    * seems there are also other fields which are not clear regarding mapping

I suggest to first define how you would like this migration to work, write a small JS code to do it and test it before dumping the data to the DB..

**Comment by OriHoch** [comment]
also, it would help to have all data in the same format, not one in csv and one in json

**Comment by OriHoch** [comment]
@mtr574 
I added a script which imports the data (https://github.com/Midburn/Spark/blob/master/bin/import_camps_data.js)
I imported the data on staging - please test

to run on production - need to deploy (it's part of the code) and then run something like this:
```
$ cd /opt/spark/latest
$ bin/import_camps_data.js camp_users.csv camps.csv
```

**Comment by OriHoch** [comment]
@mtr574 - regarding the sub-tasks you wrote, I didn't understand what needs to be done there
what use are passwords I generate and store in DB if no one will know the passwords?
also, the other points are not clear as well..

I did what I understood, and it's on staging, if you need something else please open a new issue and define properly what is needed

**Comment by natekonimbo** [comment]
@OriHoch yep. we need to work on that flow-- maybe keep it like that without password, and later send everyone email with request to create one.

the relationship user-camps code segment didn't work.

**Comment by netanelben** [comment]
Also after committing to staging, the DB gets reset..

**Comment by netanelben** [comment]
Solved by @asihud
