### ISSUE TITLE
Insert camps data into production

### ISSUE THREAD

**Issue by natekonimbo** [Midburn/spark#118]
### Background
camps module in spark isn't in-use due to lack of data,
another web-app is hosted in Firebase, using Firebase:Database services, and presented the camps index.

#### Task one
insert the camps data into the production database so the camps index can fetch the list from it, and camps module in spark will have a meaning,  specially edit camps but also (create/remove).

#### Task two
each camp should have camp manager, so we should find a solution for that too.
inserting user list and deliver password to each user's email

**Comment by OriHoch** [comment]
@mtr574 - I don't understand what's needed.. please elaborate
