### ISSUE TITLE
Authentication from drupal

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#122]
Done on the test Drupal server for now.

We need to have an SSO functionality so that we can authenticate users and bring related info.

* A view in the Drupal database that aggregates all relevant user info
* An endpoint on Spark for authenticating and consequentially retrieving user data

**Comment by OriHoch** [comment]
@omerpines / @amotenko - will be best to get access to the drupal code, I've been asking for this for a long time, what's the hold-up?

**Comment by amotenko** [comment]
@OriHoch , we can get access to the test server but not production.
It's a policy we'll have to live with.
Once the solution is ready we will be able to port it to the production server (and maybe then we'll get access :)

**Comment by OriHoch** [comment]
I don't want access to the server, I want to see the code and be able to run a local drupal environment locally

this will allow to test the integration and SSO functionality, without this development is much harder and it's possible but before diving to working like that I would like to know why...

**Comment by OriHoch** [comment]
if the hold-up is just that there is no one that can do it - I  am happy to do that

give me access to the test server and I will remove any sensitive data and upload to github

**Comment by amotenko** [comment]
Sorry for misreading.
That would be very cool. But let me just ask, when you say drupal code you actually mean the MySQL files themselves with all the table definitions, constraints and stored procedures?

**Comment by OriHoch** [comment]
no, I mean the actual drupal modules code (PHP code) - to allow running the actual drupal locally and testing the SSO functionality

just SQL data is not enough

**Comment by amotenko** [comment]
I see. I have no idea where it is but I can try to find that.
Someone also suggested to ignore the Drupal on top, and just create a view on the MySQL instance itself that will bring back the required info (and obviously connect to it from Spark). What do you think about such solution?

**Comment by OriHoch** [comment]
I think that to choose the right solution and implement it (whichever one we choose) we will need to look at the drupal php code and be able to run drupal locally

**Comment by amotenko** [comment]
I'll try to find it

**Comment by omerpines** [comment]
@OriHoch, I've opened a request for DevOps to prepare a key for you: 
http://jira.midburn.org:8080/browse/DEVOPS-10

**Comment by OriHoch** [comment]
thanks @omerpines 
@amotenko  - if you think it's worth for me to get the drupal code please let me know, I might do it anyway but it would be better to know if you think it's actually needed or not

**Comment by amotenko** [comment]
@OriHoch To be honest I'm not sure it's super useful for us, we just need to 'hack' the database, in my understanding.

**Comment by OriHoch** [comment]
no problem, I'll handle it in this issue - #131

**Comment by amotenko** [comment]
works
