### ISSUE TITLE
NPO module - inconsistent links break translation links

### ISSUE THREAD

**Issue by guywarburg** [Midburn/spark#125]
BUG - 
Due to inconsistency with the way the NPO routes builds its inner links, the rest of the application doesn't work.

### Overview of the problem
This is about the Spark **NPO module**
I am sure this issue is **not a duplicate**?

### Description
(location - routes/npo_routes.js - I believe it's line 3 but not sure)
Within the NPO routes the links handling is modified.
Instead of using full paths, the routes of NPO ignore the language part.
This means that req.url === '/npo' and not '/:lng/npo'.

(location - view/includes/page.jade - lines 30 and 35)
The translation links (flags in navbar) use a substr of the url to change language.
Therefore the generated link is wrong and causes a 404.

### Steps to Reproduce

1. Navigate to NPO
2. Try to change language.

### Expected behavior
redirect to same page with different language.

### Actual behavior
Redirect to 404 due to bad link

**Comment by guywarburg** [comment]
@amotenko - Please review and add to project / milestone if necessary.

**Comment by OriHoch** [comment]
@mickeyil - is this related to your pull request #119 ? (issue #106)

**Comment by mickeyil** [comment]
@OriHoch - it sounds like issue #106. It is fixed in pr #119.

**Comment by OriHoch** [comment]
cool! two for the price of one

**Comment by guywarburg** [comment]
Nice, didn't notice this exists already.
@OriHoch - should we close this issue or reference it in the PR?

**Comment by amotenko** [comment]
I'm closing it.
Cheers!
