### ISSUE TITLE
Add breadcrumbs to all modules - New Feature

### ISSUE THREAD

**Issue by guywarburg** [Midburn/spark#127]
New Feature - Expand current implementation to all modules.

### Overview of the problem
This is about the Spark **Users module**

### Description

In order to enable breadcrumbs in all modules we must:
1. Move the init command from camp-routes to main-routes:
`app.use(breadcrumbs.init());` - camps_routes.js line 9

2. Declare Home page - this will store a persistent home page throughout the app:
`app.use(breadcrumbs.setHome({
  name: 'home',
  url: '/' + req.params.lng + '/'
}));`

3. To any new route add to the  req a breadcrumb object or object array. Each object is made of a name and a url. The name should be the translation string. For examples see camps_routes (if not merged see PR #124 )

4. Add page names to locals.

5. In case we implement across the board - remove 'if' condition from page.jade (line 45).

6. Test links ;)

**Comment by amotenko** [comment]
Hey, this is really great!
But, keep in mind that any solution should be uniform to all Spark core modules.
So please as much as possible keep this solution portable.

**Comment by OriHoch** [comment]
nice, thanks @guywarburg - sounds good to me
