### ISSUE TITLE
midburn drupal code should be accessible at least to spark team but preferably to the world

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#131]
As I understood, the goal of Spark system is to replace the old Drupal code.

To answer this specific goal and also general use-cases which are likely to arise I think we (the spark team) should have access to see the drupal code (e.g. on GitHub) and be able to run a local instance of the drupal code

This will also help specifically in the following issues - 
* #122 - SSO between drupal and spark - having a local instance of drupal running will greatly simplify development of this feature and also prevent cycles of deploy - test - fix - re-deploy - test - fix - re-deploy etc.. instead of normal cycle of having developer testing locally and ensuring everything works before deploying.
* #95 - writing sanity end-to-end tests - without having the drupal code it will be impossible to include drupal in the end-to-end tests

**Comment by OriHoch** [comment]
I am waiting to get ssh access to the drupal test server, then I will see what we have there and decide how to continue from there

@amotenko @omerpines

**Comment by amotenko** [comment]
@OriHoch I'm with you bro

**Comment by rootux** [comment]
This will also help the dreams platform so I'm with you also.

**Comment by OriHoch** [comment]
@omerpines - I see you deleted the JIRA issue regarding giving me access
could you explain why?
is there any progress on getting access to this code?
thanks

**Comment by omerpines** [comment]
Since Nitay completed the task on the Drupal SSO API, which brings all the profile data from Drupal to Spark, I thought there is no need to access the Drupal system anymore and therefore deleted the task.
@OriHoch , Please explain the need to access the Drupal code.

**Comment by OriHoch** [comment]
drupal SSO is only 1 example of usage for having this code, this issue is more general

as described in the issue description:

> As I understood, the goal of Spark system is to replace the old Drupal code.
> 
> To answer this specific goal and also general use-cases which are likely to arise I think we (the spark team) should have access to see the drupal code (e.g. on GitHub) and be able to run a local instance of the drupal code

**Comment by OriHoch** [comment]
also, I believe in open source and having all code available.. and am willing to do the work to open source this code

**Comment by omerpines** [comment]
I'm checking this with the Drupalist.

**Comment by omerpines** [comment]
Answer from Drupalist: 

I think in general it is good to open your source code. I think in this case it is not a good idea, if it is just for git sake we have our private git repo. if it is for public knowledge then Drupal COD already have it in the open. and since we use an outdated unupdated hacked version, it only serves as an invitation to hack us using exposed known security vulnerabilities of the old code versions IMHO.

**Comment by OriHoch** [comment]
Great to know the code is available even if privately, please give us (AKA spark team) access like we asked many times before..

About open sourcing it - I guess I have to take the drupalist word for it, because I haven't seen the code yet.. Once I see it I could voice my opinion as well..

**Comment by OriHoch** [comment]
BTW - if you know about security vulnerabilities - it's even more reason to have more people accessing the code (even if privately) - to allow us to review and maybe fix or mitigate some of those problems.. It's very scary to hear that you have known vulnerabilities while people use this system for private details, payments etc..

**Comment by OriHoch** [comment]
@asihud @LeonFedotov  - regarding our chat about the automated tests, this issue will help for that use-case. 
Once we have access to drupal code + simple script (or maybe docker) to run it locally - we could include that in travis and that way we can have drupal included in automated tests without external dependencies

@ArtyomKa also had some problems where this will help - 
> The most important thing I thing is the integration with drupal. There is a set of endpoint open for us by the Drupal guys (I'll send you a link in a bit) but I can't get them to work (git myself authenticated).

**Comment by OriHoch** [comment]
I got ssh access to drupal test server

I got some dumps of data (not published because it was not screened for security yet, contact me to get it):
* apache and php configurations
* mysql dump

I tried to find the relevant Drupal code, but I got lost, here is what I got so far:
* drupal code is under /opt/bitnami/apps/drupal
  * **conf** - some app-specific apache and php configurations
  * **htdocs** - contains the actual code
    * **sites** - more midburn specific code
    * **sites/default/settings.php** - the main settings file

**Comment by OriHoch** [comment]
on hold for now, will get back to it in a few weeks (I need to get into Drupal for other projects so hopefully I will have some time to learn it a bit more)

**Comment by OriHoch** [comment]
got back to it...

**Comment by OriHoch** [comment]
https://github.com/OriHoch/midburn-profiles-drupal/blob/master/README.md#midburn-profiles-drupal

**Comment by amotenko** [comment]
@OriHoch can we close the issue?
