### ISSUE TITLE
User interface bug list and changes list

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#135]
Several Updates on the UI:

- [ ] Camps edit: details form: Field Camp Type:
       Should be changed to Multi Select instead of check box.
       Basic Information, Details, Files & Form upload, Members
- [ ] Camps Index:
      The following tabs should be displayed:    
1. for Regular user: - Join Camp (if not joined) - 
2. for Camp manager - My Camp [default]
    Shows my camp.
3. for camps admin - Create New Camp, Manage Camps [default], Camp Members, Documents & Forms

**Comment by OriHoch** [comment]
I think @amotenko can you give the permissions, you need write (AKA merge) permissions to be able to label issues

**Comment by asihud** [comment]
@guywarburg 
i am checking:

- [ ] for some reason, the create new camp submit button disappeared.
- [ ] The Camp type, still not set to Multi Select
- [ ] the Edit Camp on View Camp form, should be removed for non logged user.
- [ ] the logout button on header should be removed for non logged user.

**Comment by asihud** [comment]
more small stuff:

- [ ] to show login button on header for non logged user (link to login page)
- [ ] for non logged user, remove the username header.

**Comment by asihud** [comment]
all done by @guywarburg 
very good.
