### ISSUE TITLE
Login from drupal profile

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#147]
The procedure

- User login to the Spark/Camp system.
   First we try to check thru DRUPAL, and if not authenticated, we try old authentication.
- Once authenticated (using the /api/userlogin request), the Spark receive all the information from drupal, and updates the user profile. (Create new if not exists, and update if exists).

**Comment by OriHoch** [comment]
what happens if user profile is updated (either on spark or on drupal)?
it might create a situation where one system have some information while the other system have different information.

**Comment by asihud** [comment]
its not issue, 
every login we update the information from DRUPAL
until the spark will be the profile db.

**Comment by asihud** [comment]
okay, this task is done.
thanks to leon. (he is not on the github, we need to add him)
