### ISSUE TITLE
Updating edit camp fields and merging with new

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#152]
- [ ]  The edit.jade and new.jade doing the same. we need to merge those files, so when a change is made to the form, it will affect both.
- [x] new fields should be added on: 
   Basic Information -> Website publication
   Field input text: Contact Person Name , field on db: contact_person_name
   Field input text: Contact Person Email , field on db: contact_person_email
   Field input text: Contact Person Phone, field on db: contact_person_phone
- [x] once added fields, we need to also add on api_camps_route.js 
for api put commands: /camps/new
for api put commands: /camps/:id/edit

**Comment by guywarburg** [comment]
Closing this and opening a new detailed issue
