### ISSUE TITLE
#camps - API Access Rules - business rules!

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#177]
## A List of #camps API Commands and their access rules.
Please note, this MUST BE INCLUDED in phase#1.

### app.get('/users/:id', (req, res) => {
	Description: Get user information stated by :id
	Return: json
	

- [ ] API Access:
	logged_user.id = :id
	logged_user.role = camp_manager & logged_user.id = :id.camp.camp_manager.id
	logged_user.role = admin

### app.post('/camps/new', (req, res) => {
	Description: Creates new camp
	Return: json

- [ ] 	API Access:
	property.allow_new_camp_date < Date()
	logged_user.role = admin

	Special notes:
	if logged_user.role = admin => camp.camp_manager_id = req.camp_manager_id 
	else camp.camp_manager_id => logged_user.id

### app.put('/camps/:id/edit', (req, res) => {
	Description: Updates camp properties
	Return: json

- [ ] 	API Access:
	property.allow_edit_camp_date < Date() && logged_user.role = camp_manager && logged_user.id = :id.camp.camp_manager.id
	logged_user.role = admin
	
	properties:
	allow update for main_contact,moop_contact,saferty_contact if property value in camps.members 
            	allow update for camp_location_street, camp_location_street_time, camp_location_area if logged_user.role = admin

	
	Special Notes:
	if logged_user.role = admin , camp.camp_manager_id = req.camp_manager_id

### app.put('/camps/:id/publish', (req, res) => {
	Description: Publish the camp for anyone
	Return: json

- [ ] 	API Access:
	logged_user.role = camp_manager && logged_user.id = :id.camp.camp_manager.id
	logged_user.role = admin

### app.put('/camps/:id/unpublish', (req, res) => {
	Description: Publish the camp for anyone
	Return: json

- [ ] 	API Access:
	logged_user.role = camp_manager && logged_user.id = :id.camp.camp_manager.id
	logged_user.role = admin

### app.get('/camps/:camp_name_en', (req, res) => {
	Description: Return camp information by camp_name_en
	return: json

	
}
### app.get('/users', (req, res) => {
	Description: Return users list
	return: json

- [ ] 	API Access:
	logged_user.role = admin
        To do for phase#2: show the users the logged_user has access to: e.g. camp_manager to his camp users, with reduced properties etc. 

### app.get('/camps', (req, res) => {
	Description: Return camp list
	return: json

- [ ] 	API Access:

### app.get('/camps_open', (req, res) => {
	Description: Return camp information with status open
	return: json
- [ ] 	API Access:

### app.get('/camps/:id/join', userRole.isLoggedIn(), (req, res) => {
	Description: join logged user to camp :id
	return: json

- [ ] 	API Access:

### app.post('/camps/join/deliver', userRole.isLoggedIn(), (req, res) => {
	Description: 

	return: json
- [ ] 	API Access:

### app.post('/camps/join/request', (req, res) => {
	Description: 
	return: json
- [ ] 	API Access:

### app.post('/camps/program', (req, res) => {
	Description: Return camp information by camp_name_en
	return: json
- [ ] 	API Access:

### app.get('/camps/:id/members', (req, res) => {
	Description: Return camp :id members list
	return: json
	API Access:

### app.get('/camps/:id/manager', (req, res) => {
	Description: Return manager information of camp
	return: json
- [ ] 	API Access:

### app.get('/:lng/camps', userRole.isLoggedIn(), (req, res) => {
	Description: Return html form for logged_user
	Returns: html doc

### app.get('/:lng/camps/new', userRole.isAdmin(), (req, res) => {
	Description: Return new camp form
	Returns: html doc

        API Access: same as /camps/new API Call

### app.get('/:lng/camps/:id', userRole.isLoggedIn(), (req, res) => {
	Description: Return Camp information
	Returns: html doc

	API Access: Public

### app.get('/:lng/camps/:id/edit', userRole.isLoggedIn(), (req, res) => {
	Description: Return edit camp form
	Returns: html doc

	API Access: same as /camps/:id/edit API Call

### app.get('/:lng/program', userRole.isLoggedIn(), (req, res) => {

**Comment by LeonFedotov** [comment]
@asihud this part 
```
app.get('/users', (req, res) => {
Description: **Return users list**
return: json
```
maybe add some more description of which fields

**Comment by asihud** [comment]
if you could look:
### app.get('/users', (req, res) => {
	Description: Return users list
	return: json

- [ ] 	API Access:
	logged_user.role = admin

it should be accessed via logged_user.role=admin only.

and of course it will get improved to send the users of the camps if the logged_user is camp_manager, and to cut some properties that only admin has access to.
but at the moment, for first stage , we need to set it to admin, since we need to get a working version.

**Comment by amotenko** [comment]
it's done, or something that approximates it
