### ISSUE TITLE
Getting email information for unknown users from Drupal.

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#207]
## A scenario: 
A Camp admin send request to user to apply for his camp. 
The email is free text, and mail is sent to the user. 
Now, i need to save this information (I.e. create email to this user). 
Okay, created a user to this user, with empty details (to get his id to link him to a camp).
now, once he logged in, to approve himself, he already included, and the drupal sign will not happen.

### Solution A:
Create the user with email. flag him as not validated, and once he logged in, since he is not validated, we are doing like sign-up (validating him).

### Solution B:
Have a drupal call to know if the user has profile (and even more, get all his profile information, and make the sign-up)

Please suggest. The easiest for now, would be Solution A.

**Comment by OriHoch** [comment]
This kind of problem was discussed in the past in slack / in issues, here are 2 relevant issues where this was also discussed: #32 #147 
and also comments in this issue deals with similar problems: #131 

I believe that more hacks / patches (like ones done in the past, and like solution A in descriptioin) will give many problems and headaches.. and feels like grinding water

I think that the best way is to have more access to drupal and have the option for spark team to see and send patches to the drupal code - that way we could easily implement solution B which is much better..

I am willing to do this drupal work, and I'm waiting for reply on issue #131 to be able to do it..

**Comment by nitay-neeman** [comment]
Looks to me like a mix of A& B. 
Get the basic camp member data from the drupal api, save the uid and relevant information in your camps  table. 
 ones the camp member will log in and approve the membership  you will check your table and mark him as approved. 

No need for patches just another drupal API call🤘

**Comment by nitay-neeman** [comment]
Of course that all the api calls will be to spark  core api and it will communicate with the drupal api.

**Comment by asihud** [comment]
@OriHoch , we do not have this privilege to wait.
ofcourse option 2 is better, but can we established it today/tommorow ?

**Comment by OriHoch** [comment]
probably not but I can't know without having access to the drupal code

**Comment by ArtyomKa** [comment]
I'm currently working on getting user data from drupal, for the Volunteers
module. Drupal folks have opened an API for that:
http://jira.midburn.org:8080/browse/IT-660 there some authentication issues
that kinda give me hard time, but I hope to overcome them soon. (I hope by
today)...

**Comment by asihud** [comment]
@ArtyomKa ,
the most important thing, is to fetch the ticket information.
as at the moment, the ticket information is received when we authenticating to the drupal.

at the moment, every login updates the spark db.

**Comment by ArtyomKa** [comment]
We have ability to fetch very basic user information from Drupal  - name, email, phone number. Maybe Drupal folks can add ticket info as well on the same API.

**Comment by asihud** [comment]
okay, the lastest commits include to bring ticket information.
the problem is that it is fetched only when user is logged in.
once we will be able to bring the information to any user without authentication, it will be better.
