### ISSUE TITLE
Why are error codes and details hidden by default?

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#216]
When I access a non-existing URL, I got a generic error page.

> sorry. something went wrong :-(

After a bit of digging, I understood that the error is known within the page, only displayed in a hidden div.

What is the reason for hiding the error?
Is it a security reason?
If so, perhaps we should only apply this policy for internal sever errors (500), and for other types of errors display that to the user?

Under the current behavior, an innocent user might think the website is broken, when in fact they just followed a stale link.

**Comment by asihud** [comment]
that should be set upped as a task, 
any API Call on the code, should be checked to see that the error response are the correct one.
