### ISSUE TITLE
#devop Security issue production mysql db.

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#231]
I think that access to port 3306 on server
spark-production.cwol69gtjljp.eu-west-1.rds.amazonaws.com
should be closed to the world ip, and open only for the web access.
(even better to put vlan on our server, and open it just for the local network)

The spark mysql should not have access from the IN/OUT to any port, except 3306 (and the common ones, DNS etc)

**Comment by OriHoch** [comment]
I agree, but this was specifically requested in the past (don't remember by whom..)

**Comment by danielbenzvi** [comment]
The MySQL should never be opened to the world no matter who asks. This issue is assigned to me but I don't have access to the AWS account in order to close it. Perhaps a different Daniel?

**Comment by OriHoch** [comment]
is @danielbenzvi working on this issue?
@asihud - I see you assigned him, but this means no one else can work on the issue
if @danielbenzvi is not actively working on the issue, please remove the assignment

**Comment by asihud** [comment]
okay, removed him.
@OriHoch , you want to take this issue ?

**Comment by OriHoch** [comment]
@johnyzed

**Comment by roy-zahor** [comment]
Folks, any updates?

**Comment by OriHoch** [comment]
in new k8s environment the db is not exposed
