### ISSUE TITLE
Dockerize the spark web app.

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#24]
Dockerizing the web application can greatly reduce the installation of development environment and facilitate later deployment to staging and production environments.

There is a PR by Rudy Atias in the old bitbucket repository. Most of the feature can be taken from there.

Please comment if further discussion needed.

**Comment by ripper234** [comment]
@eyalliebermann

**Comment by OriHoch** [comment]
@ArtyomKa - are you actively working on this issue? if not, please remove yourself from assignees or update status

**Comment by OriHoch** [comment]
see this pull request which had some code for docker (it's closed because it was on hold for a long time):
https://github.com/Midburn/Spark/pull/51

**Comment by OriHoch** [comment]
done
