### ISSUE TITLE
should have some manual testing scenarios organized in a consistent and reproducible way

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#243]
### the problem
* We have a lot of people in Spark working at the same time on different stuff (AKA different modules)
  * This produces unexpected bugs and problems
    * Sometime the module a user works on is fine but his changes made problems for other modules
    * Making changes to migrations / DB can be difficult and dangerous
    * _TODO: add more examples_
* we would like to have sanity end to end tests
  * once we have some manual test scenarios setup in consistent and reproducible way it will be much easier to get help from automated tests expers to convert these to automated tests
* deployment is very risky, we would like to have check-list of scenarios to ensure everything works after deployment (AKA sanity)

### the solution
* write some testing scenarios in a consistent and reproducible way
* tests should be consistent - 
  * to allow people from different modules to both easily run them and easily modify them
* tests should be reproducible - 
  * to prevent problems of the natue of "it works on my machine"
  * tests should behave the same every time they run and on every environment

### related issues
* this is a first step towards automated end to end tests (see #95)
* having possibility to run local drupal environment will also help (see #131)

### suggested implementation
* directory called "tests"
* contains test scenarios in markdown files in a standard format
* each file contains a bunch of scenarios
* see below for a suggested example scenario

#### example scenario
* preconditions
  * drupal should have a user called "testuser" with related email "sparkstaging-midburn-testuser@mailinator.com" (this is setup on drupal test)
  * should have a spark environment connected to this drupal instance (sparkstaging is connected to drupal testing)
* forgot password scenario
  * open http://sparkstaging.midburn.org
  * click on "forgot password" link
  * enter the email "sparkstaging-midburn-testuser@mailinator.com"
  * submit
  * open mailinator inbox for this email: https://www.mailinator.com/inbox2.jsp?public_to=sparkstaging-midburn-testuser
* expected
  * should receive forgot password email
  * email should be in correct format and contain link to continue forgot password
  * clicking on the link should continue to forgot password flow for this user
  * after completing the forgot password flow and setting a new password
  * try to login to drupal with the new password (ensure drupal was updated too)

**Comment by ripper234** [comment]
+1

I'll try to make some progress on that today. Plan on using `nightmarejs.org`

**Comment by ripper234** [comment]
Started in PR #282

**Comment by OriHoch** [comment]
very nice work @ripper234 

in this issue I thought more about manual testing scenarios

while of course it's much better to have automated tests like you started writing - a lot of times these tests don't get updated / people don't add tests etc..

I think that if we had a simple directory with plain text (or markdown) step-by-step scenarios it will be easier to update and add tests

it would also be possible to require people to add scenarios for every feature they add (and they won't have the excuse of not having time to write tests.. or less of an excuse..)

**Comment by OriHoch** [comment]
IMO both this issue and #95 should remain open - they deal with different (but overlapping) issues
