### ISSUE TITLE
#gate create new API functionality for gate

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#246]
# Gate to Spark API:

On the spark user table, a current* fields were added. This describes the current user status information. The spark system has API keys to set it.

## Commands:
- [ ] /gate/event_in/id/:user_id
set the profile described by user_id to status inside event. 

### parameters:
event_id - set the event_id different from current_event_id constant.

permissions:
req.user.isAdmin === true

- [ ] /gate/event_in/email/:email
set the profile email described by email to status inside event.
### parameters & permissions same as /gate/event_in/:user_id

- [ ] /gate/event_out/id/:user_id
- [ ] /gate/event_out/email/:email
- [ ] /gate/status/id/:user_id
return the current status of user_id 

- [ ] /gate/status/email/:email
return the current status of profile email

- [ ] /gate/status/groups/:group_type/:camp_id
return the current status of group_types.
available group_types:  theme_camp, art_exhibit

returns:

- json: 
{ camp : { },
{ members: { 
    current_status : 'in',
    current_event_id: 'MIDBURN2017',
    current_status_time: (timestamp)   
  }
}

### Implementing suggestions:
on the users table, there are new fields:
current_event_id - should be constants.CURRENT_EVENT_ID
current_last_status - should be the timestamp of the position changed.
current_status - in / out 

to set the in / out information, we just need to change the fields above.

to get the information of group, use the Camps.getCampUsers, and to send out all the information of the group.

**Comment by amotenko** [comment]
yeah I think gate has all the functionality it needs
