### ISSUE TITLE
spark should allow login with auth based on drupal users

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#25]
* spark will have DB table drupal_users
  * columns: username, password
  * username is the email
* password hash - function will be supplied

### drupal_users table

```
CREATE TABLE `drupausers` (
  `name` varchar(60) NOT NULL DEFAULT '' COMMENT 'Unique user name.',
  `pass` varchar(128) NOT NULL DEFAULT '' COMMENT 'User’s password (hashed).',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT 'Whether the user is active(1) or blocked(0).'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by ripper234** [comment]
Definitely!

I know a few people did some research on this a few weeks ago.
Do you know who? If not, ask on Slack.
