### ISSUE TITLE
failed migrations should cause deployment to stop

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#252]
see this issue: #251 

it has a situations where there are errors in deploy log, but deployment continued

it's very important to ensure that deployment stops on any error

you can see how server is setup in this document: https://github.com/Midburn/Spark/blob/master/docs/development/devops.md

**Comment by amotenko** [comment]
@johnyzed can you help with this?

**Comment by OriHoch** [comment]
is @johnyzed working on it? if not, please remove him from assignees and add the up-for-grabs label

**Comment by johnyzed** [comment]
@OriHoch I am working on it. To be honest i already fixed it in my fork (https://github.com/johnyzed/Spark/commit/0f520f0d4b18c68b85fefd5f9dbee010e2226620), I just want to discuss with the guys on wednesday about a more generic solution, so I wanted to wait before submiting my PR

**Comment by OriHoch** [comment]
@johnyzed  - better to open a pull request and prefix the title with [WIP] - so we know not to merge it
WIP = work in progress

**Comment by roy-zahor** [comment]
@johnyzed Done?

**Comment by OriHoch** [comment]
in new k8s environment migrations run inside the spark pod. spark won't start until migrations ran successfully
