### ISSUE TITLE
Creating before deployment production a db backup!

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#257]
Once deployment is happening to production,
it is wise to create a backup for the spark db.

At the moment, the db is now production.
no more changes from here.
if migration will failed, we need to have a way to get back to old revision.

**Comment by OriHoch** [comment]
I don't like having backup of DB part of automated deployment - this somewhat contradicts the idea of deploy quick and often. I generally think automated deployment should be as quick and minimal as possible

We use amazon RDS for DB - I believe it has daily backup (need to verify) - which is enough in my opinion

it is also very easy in amazon RDS ui to create a backup/snapshot - so you can do that as well manually before risky deployments

**Comment by netanelben** [comment]
AWS RDS backup in buckets are the best

**Comment by OriHoch** [comment]
@johnyzed

**Comment by OriHoch** [comment]
new environment has daily db backups to Google storage
there is a k8s job which does this, it can run manually too before deployment
