### ISSUE TITLE
Critical bugs in Login screen 

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#259]
See screen capture.

Requirements:
1. Remove "Login with Facebook" button
2. Change "Forgot password" button link to Drupal reset password screen: 
Hebrew: https://profile.midburn.org/he/user/password
English: https://profile.midburn.org/en/user/password
     2.1 Phase 2: Forgot password API call to drupal
3. Change "Open a new account" link to Drupal homepage: 
Hebrew: https://profile.midburn.org/he/user/register
English: https://profile.midburn.org/en/user/register

![image](https://cloud.githubusercontent.com/assets/7349997/24838954/6da983fa-1d5a-11e7-85fd-51ba94092dba.png)

**Comment by asihud** [comment]
submitted in PR. done!
