### ISSUE TITLE
Continuous integration to run on commit

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#26]
There are a few relevant options here, a few SAAS services that are free for open source projects.

**Comment by OriHoch** [comment]
as of #28 this is done with Travis-CI
just need to activate Travis-ci for Midburn repository and it will work and run the tests on every branch and pull request

**Comment by ripper234** [comment]
Sweet!

![image](https://cloud.githubusercontent.com/assets/172282/22016400/d46150ba-dcae-11e6-921b-8d2581ea26a9.png)
