### ISSUE TITLE
Bugs in Submit request to join a camp

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#260]
See screen capture below.

Reproduction steps:
1. User requests to join a camp
2. User gets a message confirming they are pending to join the camp.

Bugs:
1. Incorrect camp displayed (I selected handycamp and got זקני השבט)

![image](https://cloud.githubusercontent.com/assets/7349997/24838948/5d8542f2-1d5a-11e7-8f1a-787acd99b552.png)

**Comment by asihud** [comment]
fixed just now on pr #261
