### ISSUE TITLE
Bugs in Spark profile screen

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#262]
See screen capture below.

Bugs:
1. Show image placeholder and allow the user to upload their image or bring image from profile or don't show any image. BUT DON'T USE RANDOM IMAGE IN PROFILE.
2. User profile should only show the camp of the user after they have been approved for the camp (I was still pending and it showed it as my camp).
3. Incorrect details coming from the Drupal about the User's Gender. 
    3.1. Also, change Sex to Gender (in hebrew מין למגדר)
4. Remove facebook and social connections section.

![image](https://cloud.githubusercontent.com/assets/7349997/24838984/3434ef32-1d5b-11e7-9583-c49ad44b9a7a.png)

**Comment by asihud** [comment]
this was fixed in PR #261 
except the random image.

**Comment by asihud** [comment]
fixed. for the random image we will consider to download images from the drupal.
