### ISSUE TITLE
Bugs in Camp details screen

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#264]
See screen captures:

![image](https://cloud.githubusercontent.com/assets/7349997/24839002/7ab24324-1d5b-11e7-8adf-8ea3f05b3dce.png)

![image](https://cloud.githubusercontent.com/assets/7349997/24839000/75189f8a-1d5b-11e7-952f-fb1c0876cd23.png)

**Comment by asihud** [comment]
uploaded in v2.1.3 release.
