### ISSUE TITLE
Bugs in Spark footer

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#266]
See bugs in screen captures:

![image](https://cloud.githubusercontent.com/assets/7349997/24839019/041e3bf4-1d5c-11e7-95da-f4e0f1ffd811.png)

![image](https://cloud.githubusercontent.com/assets/7349997/24839025/267c1d60-1d5c-11e7-8781-86ff3de5644c.png)

**Comment by asihud** [comment]
done in latest release.
