### ISSUE TITLE
Translation gaps in Spark

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#267]
See screen captures:

Camp name is displayed in Hebrew instead of English:
![image](https://cloud.githubusercontent.com/assets/7349997/24839046/6903dac4-1d5c-11e7-8d43-dec22f235148.png)

Also in user's profile: 
![image](https://cloud.githubusercontent.com/assets/7349997/24839054/81230904-1d5c-11e7-8b48-38f1998d5717.png)

Name of camp leader is in Hebrew (should have 2 fields for this in Camp details screen):
![image](https://cloud.githubusercontent.com/assets/7349997/24839040/5aef4310-1d5c-11e7-8334-c1444a368eab.png)

Join NPO screen has no translation:
![image](https://cloud.githubusercontent.com/assets/7349997/24839033/44fd1762-1d5c-11e7-8e12-cba52b97ea3f.png)

**Comment by asihud** [comment]
closed, and fixed both hebrew / english.
