### ISSUE TITLE
#camps #spark QA Requests

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#269]
### QA Request with Security Perspective
- [ ] Check that adding camp hebrew/english description strips html tags, for security reasons.
- [ ] Check that camp hebrew/english description translate http:// or mail:// to linkable.
- [ ] Check that login under regular camp user, you cannot see other members information
- [ ] Check that login under camp_manager, you cannot edit other camp (changing of url camp_id)
- [ ] Check that login under camp_member approved, you see only extra information of your camp only.

### QA Language
- [ ] Check that both english/hebrew language keys are fine.
- [ ] Suggestion of hebrew/english keys does not explainable enough.

**Comment by asihud** [comment]
please update any more testing you have in mind!

**Comment by amotenko** [comment]
will test in this round of qu
