### ISSUE TITLE
Best practice for storing server configuration

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#27]
Research and implement a solution for storing and using for deployment secret server configuration in version control.
Consider git-secret and / or other tools.

**Comment by ripper234** [comment]
Following

**Comment by amotenko** [comment]
Elad is working on this, I can't assign him for some reason

**Comment by ripper234** [comment]
Should add him to the list of contributors, I think he's not there.

**Comment by OriHoch** [comment]
@amotenko are you actively working on it? if not, please update status or remove yourself from assignees so someone else might continue work on it

**Comment by OriHoch** [comment]
using kubernetes secrets
