### ISSUE TITLE
travis should get notifications from github

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#271]
for example, look at the last commits on these pull requests:
* #126
* #110 

each commit should have a green or red check next to it - notifying about build status

looking at travis, it seems build is running but not notifying status to github

this hints towards permissions problem, but need to check

**Comment by OriHoch** [comment]
relevant slack discussion:
```
Artyom Katsap [2:21 PM] 
Hey all , does anyone know why travis ci stopped picking up PR updates?

Alex Motenko [2:22 PM] 
One sec let me look

Alex Motenko [2:44 PM] 
I can see that it's stuck but I'm not sure wny

[2:44]  
I restarted the job manually

Artyom Katsap [2:45 PM] 
it does not help. it only restarts the prev build, not new commit

Alex Motenko [2:47 PM] 
with the latest being
```99ace5c```

[2:47]  
?

Artyom Katsap [2:47 PM] 
99ace5c

[2:47]  
yes

Alex Motenko [2:48 PM] 
ok this might sound stupid but I only see `[WIP] Bookshelf mapping to volunteers` when I look in Travis under pull requests

[2:48]  
and you changed the name and removed the WIP

Artyom Katsap [2:49 PM] 
i did....

Alex Motenko [2:49 PM] 
so I would expect to see the updated title

[2:49]  
maybe try changing it back? (edited)

[2:49]  
¯\_(ツ)_/¯

Artyom Katsap [2:49 PM] 
strange, i see an updated title.

[2:51]  
are you looking at the PR tab in travis or in github?

Alex Motenko [2:51 PM] 
on travis

Alex Motenko [2:52 PM] 
uploaded this image: Capture.PNG
   Add Comment

Artyom Katsap [2:52 PM] 
oh right. that is exactly the problem. Ttravis should have triggered a new build on a new commit

[2:52]  
but it did not (edited)

[2:53]  
Bad Travis, Bad!

Ori Hoch [3:53 PM] 
@alex_motenko @artyomka
looks like some kind of permissions problem
I used to have permissions and now I don't, not sure when it happened but I guess it might be the reason
possible other settings / permissions changes might have caused it
need to log-in to travis with admin permissions and re-enable it / check for errors / review the settings

Artyom Katsap [3:54 PM] 
Who has the permissions?

Alex Motenko [3:55 PM] 
that's weird

Ori Hoch [3:56 PM] 
also, worth to notify everyone about changes to permissions, we have CI/CD processes which depend on github permissions

Artyom Katsap [3:58 PM] 
I dont think someone just changed permissions...

Alex Motenko [3:58 PM] 
was there a specific account associated with travis?

Ori Hoch [3:58 PM] 
I set it up, so it's possible it was somehow related to my account

Alex Motenko [3:59 PM] 
I don't think anybody revoked any permissions lately

[3:59]  
but sure, let's fix it

[4:00]  
does it make sense to open a user for travis?

[4:01]  
and other ci/cd related issues

Artyom Katsap [4:01 PM] 
isn't linked to Midburn organisation somehow?

Ori Hoch [4:02 PM] 
I don't know.. I usually don't add a user only for travis integration
also, we are not sure it's really the problem, need admin permissions to check

Alex Motenko [4:03 PM] 
@ori_hoch if you are not the travis admin then I don't know who is the travis admin

Ori Hoch [4:03 PM] 
travis uses github for permissions
so travis admin == github admin

Alex Motenko [4:06 PM] 
as far as I see you have write permissions

[4:06]  
I also added you to the list of collaborators just in case

Ori Hoch [4:08 PM] 
not write permissions - admin permissions

[4:10]  
also, if it's an organization, worth to check which permissions are on the organization level in github

Alex Motenko [4:11 PM] 
from what I see github only gives me nothing or everything.

[4:11]  
]there is no in between
```

**Comment by OriHoch** [comment]
need someone with admin permissions to look at the travis / github settings / permissions / integration

**Comment by amotenko** [comment]
@OriHoch granted you admin superpowers.
hope it's the right permission

**Comment by OriHoch** [comment]
had a look.. couldn't figure it out :crying_cat_face: 
will try again in a few days.. unless someone else can have a look

**Comment by LeonFedotov** [comment]
@OriHoch on it

**Comment by LeonFedotov** [comment]
@OriHoch please check if the webhooks got disabled or something, i don't have adming on the repo i cant see the settings, but from a google this seems to be the problem...

**Comment by LeonFedotov** [comment]
https://github.com/travis-ci/travis-ci/issues/7602 added an issue, @amotenko gimme them sweet powers!

**Comment by amotenko** [comment]
@LeonFedotov you got it

**Comment by LeonFedotov** [comment]
@amotenko yo! whats apiary.io ? it seems to be returning some errors on the webhook...

**Comment by amotenko** [comment]
Wasn't familiar with it until now

**Comment by LeonFedotov** [comment]
@amotenko ok im not sure it is related, can you give me admin on travis i want to flush the integration...

**Comment by LeonFedotov** [comment]
i canceled the webhook to apiray for now...

**Comment by amotenko** [comment]
you should have, it is supposed to reflect github permissions

**Comment by LeonFedotov** [comment]
@amotenko alright i re synced and now i have access...

**Comment by LeonFedotov** [comment]
ok update: nothing works for me maybe @natekonimbo can shed some light, and we can wait for the update on the issue ive created https://github.com/travis-ci/travis-ci/issues/7602

**Comment by OriHoch** [comment]
@noamr saved the day!

check out his response here: https://github.com/travis-ci/travis-ci/issues/7602#issuecomment-294014898

I guess we should just have smaller pull requests and merge quickly..

at the moment seems there are very large pull requests which are not merged - that's a problem regardless of the travis bug

I'll open an issue to deal with that

**Comment by LeonFedotov** [comment]
@OriHoch it doesn't seem like the problem is fixed even with small pr's :(

**Comment by OriHoch** [comment]
:sob: 

opened an issue regarding handling of pull requests - #292

**Comment by OriHoch** [comment]
@LeonFedotov - please link to a short pull request where it happens

**Comment by LeonFedotov** [comment]
https://github.com/Midburn/Spark/pull/273

**Comment by OriHoch** [comment]
I'm trying to build using travis api
```bash
travis login
# login with github credentials

TRAVIS_API_TOKEN=`travis token --no-interactive`
TRAVIS_POST_BODY='{
  "request": {
    "branch":"LeonFedotov-patch-1"
  }
}'


curl -s -X POST \
   -H "Content-Type: application/json" \
   -H "Accept: application/json" \
   -H "Travis-API-Version: 3" \
   -H "Authorization: token ${TRAVIS_API_TOKEN}" \
   -d "${TRAVIS_POST_BODY}" \
   https://api.travis-ci.org/repo/Midburn%2FSpark/requests
```

```json
{
  "@type": "pending",
  "remaining_requests": 10,
  "repository": {
    "@type": "repository",
    "@href": "/repo/11538810",
    "@representation": "minimal",
    "id": 11538810,
    "name": "Spark",
    "slug": "Midburn/Spark"
  },
  "request": {
    "repository": {
      "id": 78048635,
      "owner_name": "Midburn",
      "name": "Spark"
    },
    "user": {
      "id": 64706
    },
    "id": 66631352,
    "message": null,
    "branch": "LeonFedotov-patch-1",
    "config": {
    }
  },
  "resource_type": "request"
}
```

**Comment by OriHoch** [comment]
of course there was a silly mistake in last comment, now it works - editted the comment ^^

**Comment by OriHoch** [comment]
of course I also exposed my token.. :palm_tree: :face_with_head_bandage:

**Comment by LeonFedotov** [comment]
@OriHoch WOAH how you did it it did work!

**Comment by LeonFedotov** [comment]
#273

**Comment by OriHoch** [comment]
ok, so, results of my investigations so far:
* travis works fine, you can start a build manually on travis using the code I wrote above
* the problem is that github does not notify travis to start a build

The only thing I haven't ruled out is the whole Midburn organization permissions

This still looks like some kind of permissions or settings problem on the organization level.

I think that only someone with full owner permissions on Midburn organization will be able to fully investigate this.

**Comment by OriHoch** [comment]
ok, I got full owner permissions, looking into it again now

**Comment by asihud** [comment]
@OriHoch 
it seems the issue is not solved.
if i want to upload & deploy release, what is needed to send in the TRAVIS_POST_BODY ?

TRAVIS_POST_BODY='{
  "request": {
    "branch":"LeonFedotov-patch-1"
  }
}'
it seems that changing the branch to v2.2.2 , works fine on the travis testing, but it does not deploy it for spark (or givving it different name).
can we have a solution for that , or i will need to upload the release manually ?

**Comment by OriHoch** [comment]
full details about the travis request body are here - 
https://docs.travis-ci.com/api#requests

I think you will need to do something like this:
```sh
TRAVIS_POST_BODY='{
"request": {
"tag":"v2.2.2"
}
}'
```

you can also deploy manually without travis

**Comment by asihud** [comment]
@OriHoch 
it doesnt seems to be working.
i'll try to put both branch and tag, and see if it is happening.
(for some reason, it did not execute at all)

**Comment by OriHoch** [comment]
I updated the title - it seems the issue is more general, and travis doesn't get any notifications from github

same problems happens with Codeship - I set it up for Midburn/Spark and - same problem.. I opened a support request for Codeship, hopefully they will shed some light on the issue

At the moment, we have workarounds which allow us to work with this problem, see in comments on this issue or ask on slack

I don't think there is anything else to do now but wait.. for either Travis or Codeship to respond on the support requests..

**Comment by OriHoch** [comment]
the issue is that Midburn organization was downgraded to free plan while still having private repositories

GitHub blocked all web hooks 

Need Midburn org to sort out the billing / delete the private repositories

**Comment by OriHoch** [comment]
ok, looks like github removed the limitations, integrations seem to work now
