### ISSUE TITLE
Spark Roadmap 2018

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#274]
Next year Spark is going to be faster, stronger, and better.
We are also going to rewrite everything in Rust.

Please add here all the ideas you had and would like to see happening in Spark 2018, starting from technical issues like 'better tests', 'finally getting to fixing that bug' and 'rewrite everything in Rust' up to products and systems that can be implemented on top of Spark.
Be specific where possible!

**Comment by roy-zahor** [comment]
"rewrite everything in Rust" --- Why? What's wrong with JavaScript? Rewriting everything sounds bad for me.

**Comment by amotenko** [comment]
Hi!
Rewrite everything in Rust is a joke.., albeit not a good one.
