### ISSUE TITLE
Spark - Manage Camps - Manage Members - The dropdown is appearing upwards and is cut

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#275]
Bug

This is about the Spark **Camps module**
My **browser** is: Chrome 57.0.2987.133

### Description
Dropdown is appearing upwards and is cut (See screen capture)

![image](https://cloud.githubusercontent.com/assets/7349997/24929511/e17eae3a-1f0e-11e7-82d2-c34cbd6443e1.png)

**Comment by amotenko** [comment]
I don't think we have this element any more
