### ISSUE TITLE
Spark - Manage Camp - Edit Camp

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#276]
BUG
Camps module
Description: Show description field as expanded (See screen capture)
![image](https://cloud.githubusercontent.com/assets/7349997/24932476/63fd1d3c-1f1a-11e7-80aa-14a44f83d1c9.png)

**Comment by ripper234** [comment]
I failed to start working with camps due to missing data (#284)

**Comment by amotenko** [comment]
@ripper234 were you able to add a camp?

**Comment by ripper234** [comment]
I wasn't able to access the camps admin page and enter any data. The process is too complicated right now (see #284 ).

**Comment by asihud** [comment]
@guywarburg , see if you can pick this small issue.
