### ISSUE TITLE
Bug: Camp Management - Camp members - Warning text appears in both Hebrew and English

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#277]
BUG
CAMPS MODULE
Reproduction steps:
1. Go to a camp.
2. Cancel membership of a camp member. 
3. A warning message appears.

Expected: Message will display text in Hebrew or English, depending on the user's interface language.
Actual: Message appears with both Hebrew and English (See screen capture)

![image](https://cloud.githubusercontent.com/assets/7349997/24947133/4d737710-1f6e-11e7-8936-38402a0e2e75.png)

![image](https://cloud.githubusercontent.com/assets/7349997/24947157/6a411294-1f6e-11e7-82c9-d3954520acec.png)

![image](https://cloud.githubusercontent.com/assets/7349997/24947235/a5d9ed62-1f6e-11e7-9c82-743756a86224.png)

**Comment by asihud** [comment]
fixed in latest PR
