### ISSUE TITLE
Spark Camps - Manage Camp - Add new members does not work

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#278]
Adding the member's email and clicking the Add new member CTA button does not do anything. See screen shot below.

![image](https://cloud.githubusercontent.com/assets/7349997/24949601/dff3d992-1f76-11e7-9cff-396d83a27d6b.png)

**Comment by asihud** [comment]
omer, 
this can happen if the added member, 
is assigned to different camp.

**Comment by asihud** [comment]
okay, found the bug. fixed, will be uploaded in the next PR.
you are member in more than one camp.
