### ISSUE TITLE
Spark should move towards OAuth

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#281]
In the distant future

**Comment by OriHoch** [comment]
please provide some details - 
* why OAuth specifically?
* what's the use case specifically for OAuth
* how it related to other SSO issues like #279 / #288

**Comment by OriHoch** [comment]
#### related / possibly duplicate issues
* #279 - Spark should provide real SSO functionality
* #288 - Implement sso functionality

**Comment by OriHoch** [comment]
I'll be working on issue #288

**Comment by LeonFedotov** [comment]
ok closing this as duplicate of #288
