### ISSUE TITLE
Volunteers session integration

### ISSUE THREAD

**Issue by LeonFedotov** [Midburn/spark#283]
- [ ] Dynamic **(with token)** link to the volunteers from spark front-end
- [ ] api identifies user per token - provides token => id
- [ ] /me api thats provides volunteering info from the volunteer table in spark db
- [ ] The token need to be validated each api call from volunteer to spark

**Comment by LeonFedotov** [comment]
@amotenko says: 
> the session id needs to be part of each api-call from volunteers to spark and returned with the response

**Comment by OriHoch** [comment]
#### related issues
* #288 - Implement sso functionality
