### ISSUE TITLE
Implement sso functionality

### ISSUE THREAD

**Issue by LeonFedotov** [Midburn/spark#288]
spark should provide single-sign-on abilities for out modules (volunteers, dreams)

**Comment by OriHoch** [comment]
#### related / possibly duplicate issues
* #281 - Spark should move towards OAuth
* #279 - Spark should provide real SSO functionality

**Comment by OriHoch** [comment]
@LeonFedotov @amotenko @rootux @omerpines 
I'll write a specification / implementation guide for this

**Comment by OriHoch** [comment]
Wrote the spec here:
https://github.com/Midburn/Spark/blob/master/docs/usage/SSO.md

let me know what you think..

**Comment by amotenko** [comment]
we have it, kind of
