### ISSUE TITLE
pull requests should be small and merged quickly

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#292]
at the moment seems there are very large pull requests (e.g. a lot of commits, open for a long time), some examples:
* #126 
* #270 

### TODO
* figure out why it happens
* update the contribution guidelines and the maintainers guidelines - 
  * each pull request should have a related issue
    * the related issue should be well-defined, to the point, and with a clear outcome
    * (it's ok not to have related issue, if you describe it in the pull request)
  * project maintainers - the ones doing the merge
    * should respond to pull requests quickly (within a few days)
    * if they are not available - respond that they are not available and when they will be available
    * a clear decision must be made on every pull request (within a week)
      * This decision must be one of:
        * merge the pull request
        * reject the pull requst - and write specific things that needs to be fixed
        * reject the pull request - and write specifically why it's rejected

**Comment by amotenko** [comment]
I agree, it is a good practice

**Comment by ArtyomKa** [comment]
Question here. I opened the PR that has many commits, but I think the
problem is, not that I made a lot of commits, actually I changed several
files only, but most of the commits came from the upstream as I was
regularly pulling changes from the master. Is this a bad practice and I
should have merge upstream only when I was finished?

**Comment by OriHoch** [comment]
@ArtyomKa what you need to do when starting working on a feature / bug fix / anything that will result in PR
* go to master branch - `git checkout master`
* pull latest changes from midburn master - `git pull midburn master`  (assuming you have a remote named "midburn" which points to Spark/Midburn Github repo)
* create a new feature branch - `git checkout -b 123-my-feature-or-bug-fix-title`
* make commits on this branch, push to your fork
* be sure to pull latest changes from midburn master - preferably before every push
* push to the feature branch on your fork
* open a pull request (from your fork's branch to midburn master branch)
* go back to master, and continue on the next feature the same way..
