### ISSUE TITLE
Test files should be concentrated in one folder

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#297]
### Overview of the problem

Problem with the tests,  tests possibly failing.
### Description

Right now there test files are spread across the code base: 
there is _test_ folder containing e2e tests
there is _tests_ folder containing unit tests
there are several more test files in the _routes_ folder

### Expected
I propose to create following structure:
```
tests
|____unit
|      |____models
|      |____routes
|____e2e
       |____<<subfolder per scenraio or a subsystem maybe>>
```

**Comment by amotenko** [comment]
done, right?
