### ISSUE TITLE
A link to join slack

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#30]
`joinslack.midburn.org` (or something similar) should be an easy link to join our Slack.

Waiting on Goldi for this one for a decision.

**Comment by amotenko** [comment]
@ripper234 why from Spark though?

**Comment by ripper234** [comment]
Why is the issue in this repo? Because we're migrating away from Asana, and this is the best place I found to put the ticket. It's relevant to Spark because it will help new Spark contributors find our Slack (and the Spark readme should be updated)

Do you have a better suggestion?

**Comment by amotenko** [comment]
@guywarburg is working on a page for Midburn Tech as a part of the midburn website that will have info about our projects as well as contact info and of course a 'join slack' link.

**Comment by ripper234** [comment]
@amotenko we still need to create the link, which requires work in itself.

@OriHoch can you help with this?

**Comment by amotenko** [comment]
@ripper234 Ron, this is not the place for this issue. Please close it.

**Comment by ripper234** [comment]
Can we talk about it tonight?
