### ISSUE TITLE
Camps - Facebook share looks wrong

### ISSUE THREAD

**Issue by rootux** [Midburn/spark#322]
Apparently the og:description tag is not being used - I believe it's something related to the iframe - not sure but it looks bad when shared.

![18051999_10209801657853548_958760809_n](https://cloud.githubusercontent.com/assets/1032526/25242202/7bda3a96-2601-11e7-8dcd-d3438943b711.png)

**Comment by OriHoch** [comment]
it's a share from Feb. 13 - I think it works OK now

![image](https://cloud.githubusercontent.com/assets/1198854/25288424/0a17dfb2-26ce-11e7-84c7-a79db4f0220f.png)
