### ISSUE TITLE
[Task] review the nginx / node production configuration (focus on stability and performance)

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#326]
We got some problems of web app crashing unexpectedly
See summary of this issue here: #323 

Need to review the nginx and node configurations and see if something there might cause problems

### TODO
ssh to the spark production server
- [ ] review nginx configuration (/etc/nginx)
  - including all relevant configuration files
  - including the spark site configuration
- [ ] review the node server configuration (/etc/systemd/system/midburn-spark.service)
  - including the start.sh script
  - including the spark web-app itself (/opt/spark)

**Comment by OriHoch** [comment]
@LeonFedotov suggested to use forever

**Comment by LeonFedotov** [comment]
https://github.com/foreverjs/forever 👋

**Comment by amotenko** [comment]
not crashing anymore, I think
