### ISSUE TITLE
[Task] remove the old spark production instance after we are sure the new load balancer works and dns was propogated

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#329]
in [v2.2.3](https://github.com/Midburn/Spark/releases/tag/v2.2.3) we changed to use a load balancer + autoscaling group

the old spark production instance is still running to ensure smooth transition

after 48 hours - if everything is in order, the old instance can be terminated

**Comment by amotenko** [comment]
well, it's gone now
