### ISSUE TITLE
Add a technical description of Spark's (desired) architecture and mission statement

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#33]
I'm on the motherfucker

**Comment by ripper234** [comment]
+1

Following

**Comment by ripper234** [comment]
(talk to me if you want help)

**Comment by amotenko** [comment]
First draft is here

https://docs.google.com/document/d/11eETwSJrDBvQkD8IKL8h3EHdZhLa8MFD3DMElvWrleE/edit#heading=h.6syw8ttdft1y

**Comment by OriHoch** [comment]
@amotenko - why did you close it?
if the manifesto is complete then publish it on github

**Comment by amotenko** [comment]
I wouldn't say it's completed but I sure will post it here. needs to be
translate it to markdown though
