### ISSUE TITLE
[Task] Deploy new Spark version to Production

### ISSUE THREAD

**Issue by omerpines** [Midburn/spark#335]
This is about the Spark Theme Camps module / Core

### Description

Deploy the latest Spark version (currently deployed to Staging, ver 2.3.0 [Updated]) to the production servers. 

Note that we now have two production servers with load balancing. Deploying instructions: https://github.com/Midburn/Spark/blob/master/docs/development/releases-and-deployment.md#deploying-a-published-release

**Comment by OriHoch** [comment]
@omerpines  - v2.2.3 is on production

staging is always updated with every push to master (discussed to stop this at some point, don't know what happened with that)

currently there is a draft release (v2.3.0) - you can see it on releases page - https://github.com/Midburn/Spark/releases

this release should be published, and then we can deploy it

**Comment by OriHoch** [comment]
the releases and deployment document you linked to contains all the details regarding this process - publishing a release, merging etc..
https://github.com/Midburn/Spark/blob/master/docs/development/releases-and-deployment.md

**Comment by OriHoch** [comment]
also, I'm pretty sure release notes are not updated, which I believe should be required before publishing a release

**Comment by asihud** [comment]
@OriHoch 
i've published the release. 
Would you be kind enough to upload the release ?

/spark-deploy v2.3.0
command from the bot, return an error:
<div id="content">
<p>The following error was encountered while trying to retrieve the requested URL:</p>
<blockquote id="error">
<p><b>[Error Code: 1008] Connection to the client IP address failed.</b></p>
</blockquote>
<p>The remote host or network may be down. Please try the request again.</p>

Can the IP provided, or where to change the slack bot config so it will work as the documents note ?

**Comment by OriHoch** [comment]
please read the deployment document that @omerpines linked to above - we now have different more complex configuration with load balancer and autoscaling group and the deployment process changed

**Comment by asihud** [comment]
@OriHoch ,
I've read the document, but the documents is not clear enough to do the process and i myself do not understand much about it.
who wrote the document, or has all the information to execute it ?

**Comment by OriHoch** [comment]
I wrote it, you can try to get DevOps people to help - it uses standard AWS methods for deployment

I'll be able to do it tonight

**Comment by omerpines** [comment]
Escalated to DevOps team: http://jira.midburn.org:8080/browse/DEVOPS-25
Also requested in Slack.

**Comment by OriHoch** [comment]
version v2.3.1 was deployed
