### ISSUE TITLE
should change to a stable NodeJS version

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#346]
@noam-almog wrote:
> as for node crashing for no good reason, we are using node 7.4 which is by definition unstable, we should either consider downgrading to 6.10.2 or upgrade to latest unstable release (7.9)

**Comment by roy-zahor** [comment]
We are now using node features that are not available in 7.4.0. So, in .nvmrc file I have updated to 7.9.0.
Production server needs to be updated as well, see https://github.com/Midburn/Spark/issues/371

**Comment by noam-almog** [comment]
@roy-zahor 7.10.0 is out, better to use it, no ?

**Comment by roy-zahor** [comment]
@noam-almog I guess you are right

**Comment by roy-zahor** [comment]
The issue is closed, but I comment to have a documentation:
As discussed yesterday, we will keep 7.9.0 at least for the next month up until the event.
