### ISSUE TITLE
Travis Slack integration

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#35]
Whenever a build fails, or passes for the first time after a failure, Travis should post to #sparksystem-alerts channel on Slack. 

Make sure no excessive messages (we don't want to annoy people).

[] Add all spark devs to sparksystem-alerts (if anyone wants to leave they can)
[] Add #sparksystem-alerts as a default channel for new devs on Slack
[] Nice to have: if you personally broke the build, you get a pm.

**Comment by OriHoch** [comment]
@amotenko  - I'm already working on it.. will publish a pull request soon
re-assigning back to me..

**Comment by OriHoch** [comment]
in #45 I added notification to slack on every build of master

**Comment by OriHoch** [comment]
continuing to work on it with the staging server

**Comment by OriHoch** [comment]
basic auto deploy is working on staging, relevant documentation:
https://github.com/Midburn/Spark/blob/master/docs/development/devops.md

**Comment by OriHoch** [comment]
@amotenko  - why did you close it?

**Comment by amotenko** [comment]
if I'm not mistaken we got everything , but correct me if I'm wrong

**Comment by OriHoch** [comment]
I didn't open this issue but AFAIK some points from original description are not done yet:
[] Add all spark devs to sparksystem-alerts (if anyone wants to leave they can)
[] Add #sparksystem-alerts as a default channel for new devs on Slack
[] Nice to have: if you personally broke the build, you get a pm.

we have some limited integration, but I'm not sure what was the original intent

**Comment by OriHoch** [comment]
I usually let the original reporter (in this case @ripper234) close the issue or at least give him a chance to respons before closing to make sure no idea is left behind..

also, explaining why issue is closed is required in my opinion for correct working flow

**Comment by ripper234** [comment]
Thanks @OriHoch.
@amotenko : I agree that in general when closing, an explanation should be mandatory.

However in this case I'm not really a part of the workflow these days, so I have no objection to closing if @amotenko wants. Closing it for now.

**Comment by amotenko** [comment]
@ripper234 , @OriHoch I know it sounds retarded but I wasn't aware of this aspect of open source project etiquette, so thank you for pointing this out.
Regarding the bullets above, I may be biased and please tell me if you feel that's wrong but I think that 'noise' should always be opt-in and not opt-out, especially for newcomers.
Regarding the last bullet, today with Travis we can't push a branch if it's breaking a build, so is this scenario possible?

**Comment by ArtyomKa** [comment]
BTW, if everyone sets up Travis for their own fork of the repo, we will
have very little CI failures.

**Comment by OriHoch** [comment]
@ArtyomKa - spark's travis runs on pull requests so you don't have to configure travis for each fork
you just have to open a pull request and mark it as in progress so it won't be merged..
