### ISSUE TITLE
should have documentation / guide regarding how to use the knex migrations

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#350]
we ha(ve|d) some problems with misuse of the migrations system (hopefully we will fix the current problems)

 we should have good documentation to prevent these problems from happening again

maybe there is some existing intro to migrations we can link to

the problems were both specifically with Knex but also generally with what migrations are and how they should be used

**Comment by amotenko** [comment]
we cannot write documentation on how to use knex better than the maintainers of knex, (I mean, we could but it wouldn't be cost effective)
