### ISSUE TITLE
Spark Dev should allow reverting to a known state of the database

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#351]
Today we have a problem of running tests locally against a mysql database. Unlike when we used sqlite we don't have a solution to reset the database to a known, populated state, yet.

**Comment by OriHoch** [comment]
how did we do it for sqlite? i was not aware of any existing method to do that for sqlite

generally, we should use knex so it doesn't matter  if it's sqlite or mysql

**Comment by ArtyomKa** [comment]
sqlite was using a different file for tests. Running `npm test` was deleting the file, running migrations and executing the tests.
I think something similar should be here... using separate db for tests (say `spark_tests`) running some script  that drops the db if it exists, running migrations and then tests.

**Comment by roy-zahor** [comment]
@ArtyomKa @amotenko 
https://github.com/Midburn/Spark/pull/355 Might solve this.
Pull from master and run **npm run-script createdb**. This should bootstrap a new DB, so you will be able to run knex migrate:latest without any problems. If you find any errors, please comment and tag me.

**Comment by OriHoch** [comment]
@ArtyomKa - yes, what you said is what we need..
