### ISSUE TITLE
Spark should provide a button to redirect to volunteers homepage

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#353]

**Comment by amotenko** [comment]
That looks like the button for campa

**Comment by ArtyomKa** [comment]
The button was created and now points to the correct url: http://volunteersstaging.midburn.org, but 
 redirects from there back to spark.
I think has something to do with the cookies mechanism. 
@noam-almog

**Comment by ArtyomKa** [comment]
Implemented. Can be closed
