### ISSUE TITLE
Admin panel for Users

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#36]
Spark should provide an admin panel for easy manipulation of users

**Comment by OriHoch** [comment]
a few questions:
1. what kind of manipulations would you expect to do?
2. who will do these manipulations - only tech people or we should support also non technical users?
3. Would a simple DB UI be enough?

**Comment by OriHoch** [comment]
Personally my go-to tool for these kinds of UIs is Django Admin..

**Comment by ripper234** [comment]
I think a simple DB UI should be enough for the MVP.
Of course we do need a more sophisticated admin panel, the question is whether it's a MUST HAVE for launching Camps.

**Comment by amotenko** [comment]
0. indeed Django admin panel is both a pleasure and delight to use
1. I expect there will be problems with drupal migration and it will be very handy to edit users
2. developers and maybe system administrators
3. From UI point of view, since every module in Spark will have to include an admin panel to manipulate data directly but also to perform various admin actions (for example, in Camps, admin needs to review and approve camps) a simple DB UI is not sufficient.

**Comment by OriHoch** [comment]
There aren't many options for ready to use admin panels in node JS.

I tried the following options:

* [express-admin](https://simov.github.io/express-admin/), I tried to use it but it's a mess, very limited and hard to use, work I did on it so far is in this branch - https://github.com/OriHoch/Spark/tree/express-admin

* [gentelella](https://github.com/puikinsh/gentelella/blob/master/README.md) - provides only UI components, so backend needs to be implemented. I think this is the way to go, even though it requires some more work on backend. It looks great and with more setup work will allow to easily add admin componnets. I started working on it in this branch - https://github.com/OriHoch/Spark/tree/gentelella-admin

I think the gentelella based admin with basic functionality should be ready sometime next week.

Another option is Django admin - I can get it setup in a couple of hours and it will provide everything you need and more..
