### ISSUE TITLE
Volunteers migrations.

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#366]
### Overview of the problem
Migrations on staging DB fail. 

I tried to recreate the volunteers tables. Created PR #358 adding to migrations files - One creating 3 tables and another one setting up the relations. (two FK).
Everything worked on a clean DB. tests pass, so I merged the PR. Migrations failed on staging because DB still contains tables from previous migrations problem (which I thought where dropped during the resolution). So I reverted the PR (twice).  Added dropping tables to migrations, created another tried to merge again - similar problem. We are again at the situation that the migrations do not represent DB state.

I think the best approach is to drop volunteers tables:
```
vol_departments       
vol_departments_roles 
vol_schedule          
vol_shifts            
vol_types_in_shift    
volunteers            
volunteers_delete
```
delete the last migration from `knex_migrations` table and rerun the deployment
but this means messing with the DB manually, bypassing the migrations.

@OriHoch @roy-zahor. Please advise.

**Comment by OriHoch** [comment]
yes, I think that's what we need to do - fix the DB state manually and sync it to migrations state

This should be done in relation to all tables, including camps, volunteers etc.. which also had these problems

bottom line, need to do the following manually on both dev and production environments:

* editing knex migration table manually - and "faking" that all migrations ran
* manually making sure the migrations match the DB state

effectively resetting the migrations to a clean and known state - then, once that's done - need to ensure that everyone uses migrations system correctly

I think we had issues dealing with this, not sure what's the status

let me know if you need my help..

**Comment by ArtyomKa** [comment]
I've done as suggested. Deleted all volunteers tables. Deleted from `knex_migrations` table the last line from partial migration. Restarted the build on Travis -> build and deployment passed.
