### ISSUE TITLE
[Task] should ensure production environment uses the .nvmrc file

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#371]
see #370 - there was a problem on staging that it didn't use the .nvmrc file

should ensure this is fixed on production as well

for production it's a bit more complicated - might need to create a new AMI file

**Comment by LeonFedotov** [comment]
@OriHoch i'm not sure how to validate this.

**Comment by OriHoch** [comment]
in the syslog you can see the running node version

this is on stage, should be similar on production (maybe grep for "node v")

```
$ tail /var/log/syslog | grep start.sh
May 11 14:39:26 localhost start.sh[19532]: Found '/opt/spark/latest/.nvmrc' with version <v7.9.0>
May 11 14:39:26 localhost start.sh[19532]: Now using node v7.9.0 (npm v4.2.0)
```

**Comment by LeonFedotov** [comment]
Seems to work now, but I manually created the AMI that points to stable and installed 7.9.0

**Comment by amotenko** [comment]
@OriHoch what's up with that?
