### ISSUE TITLE
Some migrations are failing in production due to insufficient permissions of the spark user

### ISSUE THREAD

**Issue by LeonFedotov** [Midburn/spark#381]
Hello, some migrations failed due to missing permission of the spark user, seems like `CREATE TRIGGER` requires super privileges.
two possible solutions: 
A: run the migrations as root.
B: add super to spark user.
@OriHoch please advice.
attached error message:
```
Error: ER_BINLOG_CREATE_ROUTINE_NEED_SUPER: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
```
```
Knex:warning - migrations failed with error: CREATE TRIGGER camp_members_groups_after_ins AFTER INSERT ON camp_members FOR EACH ROW BEGIN INSERT INTO users_groups_membership (group_id, user_id) VALUES (new.camp_id, new.user_id); END - ER_BINLOG_CREATE_ROUTINE_NEED_SUPER: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable) 
```

**Comment by LeonFedotov** [comment]
@ArtyomKa @roy-zahor @asihud FYI

**Comment by roy-zahor** [comment]
It appears that this error is probably related to Amazon configurations:
http://stackoverflow.com/questions/11601692/mysql-amazon-rds-error-you-do-not-have-super-priviledges

**Comment by roy-zahor** [comment]
@LeonFedotov @OriHoch 
Amazon official article about this:
https://aws.amazon.com/premiumsupport/knowledge-center/rds-mysql-functions/
There are some security concerns when enabling triggers, so we must restrict the mysql socket of the db to localhost only.

**Comment by LeonFedotov** [comment]
for me to follow the tutorial i need more privileges im getting 
`User: leon is not authorized to perform: rds:DescribeDBInstances (Service: AmazonRDS; Status Code: 403; Error Code: AccessDenied;`

**Comment by LeonFedotov** [comment]
Done, followed the [stackoverflow](http://stackoverflow.com/questions/11601692/mysql-amazon-rds-error-you-do-not-have-super-priviledges) @roy-zahor posted.
