### ISSUE TITLE
#Camps: add export to excel for all tables

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#389]
## Export to Excel/CSV
this small task is to implement on angular tables
(on admin: camps-admin)
add an export to excel button, on click, will take all displayed data on the grid, and will export them to excel.

* This task is very critical, because it gives department manager to export their data and do statistic on it.

**Comment by amotenko** [comment]
will not be implemented

**Comment by OriHoch** [comment]
this functionality will be provided for all midburn DBs by the [midburn-k8s business intelligence chart](https://github.com/Midburn/midburn-k8s/tree/master/charts-external/bi#midburn-business-intelligence)

**Comment by amotenko** [comment]
@OriHoch  my bad, this functionality already exists

**Comment by OriHoch** [comment]
this functionality is now also available by the BI service at https://production.midburn.org/metabase/
