### ISSUE TITLE
#Spark: Create event properties editor

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#390]
## Event_id editor
As we all know, the current event_id field that is set to MIDBURN2017,
is installed on the constants, and soon to be removed and all its information is stayed in the events table.

on the events table, there is json_data field which hold all the event specifiec information.
The information is usually, enable/disable for some features on the event.
the json_data should be:

{ "groups": { "theme_camps": { "property1": "data1"}}, "start_date": "2017-28-05", "end_date": "2017-06-02"}

- [ ] Add a new tab to camp admin manager with a form, on this form we need to put, one checkbox, one datetime picker, one input, and one select. this will be used as template.
- [ ] Post of this form will execute /event/:id properties API camps.
- [ ] The post will save its relevant data to the db, on the appropriate place on the json_data.
- [ ] the following options are needed for the camp:
1. disable_user_add_to_group [boolean options: false/true] 
2. user_add_to_group_allow_statuses [string options: open/closed default: 'open','closed']
3. disable_admin_add_to_group [boolean options: false/true]
4. admin_create_new_group [boolean options: false/true]

**Comment by amotenko** [comment]
done
