### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#40]
It needs a re-haul.

- [x] tech stack
- [x] help wanted
- [ ] code review process
- [ ] ...

**Comment by ripper234** [comment]
What else do we need?

**Comment by ripper234** [comment]
@OriHoch I did some work on Readme today, then saw the [CONTRIBUTING](https://github.com/Midburn/Spark/blob/master/CONTRIBUTING.md) docs we have. Readme should probablly link to them, not sure whether currently there is a duplication.

**Comment by OriHoch** [comment]
yeah, should have a link from README

**Comment by ripper234** [comment]
Not really relevant anymore, most of it is covered by the dev guide.
