### ISSUE TITLE
gzip of responses should be done at load balancer or web server

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#402]
following PR #400 all responses are gzipped by nodeJS (part of the app JS code)

AFAIK it's better to do this at the load balancer, or in nginx

also, in the future we will probably want to serve static files via Nginx and not via Node - in that case gzip will have to be at nginx level anyway

**Comment by amotenko** [comment]
what's up with that?

**Comment by amotenko** [comment]
@OriHoch
