### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#41]
MIT/Unlicense?

**Comment by OriHoch** [comment]
interesting question - which open source license is most compatible with the burning man principles

**Comment by OriHoch** [comment]
MIT allows for most freedom
but maybe the restrictive ones are better because we won't to prevent commercialization.. in that case I would go with AGPLv3

**Comment by ripper234** [comment]
Interesting. I suggest we open this discussion up on Slack.

**Comment by ripper234** [comment]
See also http://choosealicense.com/

**Comment by ripper234** [comment]
We'll discuss this this upcoming Wednesday, I'll make/find a presentation about it.

**Comment by ripper234** [comment]
I did some research and prepared this presentation.

https://docs.google.com/presentation/d/1GMAiyDT14XlSKXtTiDULqTgceEFzo6H4bM1NVW593Ng/edit?usp=sharing

The TL;DR is that Apache seems to be my personal favorite. Will present it tomorrow evening.

**Comment by ripper234** [comment]
@OriHoch can you review?

**Comment by OriHoch** [comment]
looks good

**Comment by ripper234** [comment]
@OriHoch what do you think of the last slide? I raised a few questions there.

**Comment by amotenko** [comment]
@ripper234 so have we added the license eventually?

**Comment by ripper234** [comment]
No, this is pending on Goldi / Omer.

**Comment by amotenko** [comment]
Let's say we pick one, how do we actually add it ?
Is it just a footnote somewhere or does it require stamping each and every source file?

**Comment by OriHoch** [comment]
IIRC the standard is a LICENSE file in root of the project

**Comment by amotenko** [comment]
@ripper234 can you make this happen? we **_do_** need a license.

**Comment by amotenko** [comment]
Here is a reference for future me

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by ripper234** [comment]
It's stuck with Goldi/Midburn legal... I have zero power to move this except bugging Goldi :)
I'll ping him now again.

**Comment by ripper234** [comment]
I didn't find Goldi's nick here, assigning to @omerpines in the meantime ... I can't make progress on this issue.

**Comment by OriHoch** [comment]
done in #285
