### ISSUE TITLE
gate ui

### ISSUE THREAD

**Issue by LeonFedotov** [Midburn/spark#419]
- [x] quota count is missing in edit [1]
- [x] after editing production groups they get reclassified as camps [2]
- [x] quota change is not saved 
- [ ] under gate search ticket count is not correct [3]

---
# 1
![screen shot 2017-05-20 at 12 57 55](https://cloud.githubusercontent.com/assets/130342/26274844/37549e12-3d5c-11e7-9011-ec16760cdc08.png)
# 2
![screen shot 2017-05-20 at 12 58 32](https://cloud.githubusercontent.com/assets/130342/26274856/6cf2235a-3d5c-11e7-91d1-ba172d0f08c8.png)
# 3
<img width="1135" alt="2017-05-20_1244" src="https://cloud.githubusercontent.com/assets/130342/26274827/dc494c98-3d5b-11e7-935b-cfa8c97f8cb4.png">

**Comment by amotenko** [comment]
Need to check if still an issue

**Comment by amotenko** [comment]
Closing old issues and opening new tickets for UI issues:

https://github.com/Midburn/spark/issues/632
https://github.com/Midburn/spark/issues/633
https://github.com/Midburn/spark/issues/634
