### ISSUE TITLE
[Task] investigate latency spikes on production load balancer

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#435]
there are massive latency spikes of up to 60 seconds

data for last 3 hours, per minute

![image](https://cloud.githubusercontent.com/assets/1198854/26283122/50ed3e5a-3e2a-11e7-9b28-e16112a2cbb9.png)

**Comment by LeonFedotov** [comment]
im suspecting its the sync scripts, and the deploys

**Comment by OriHoch** [comment]
do you have somewhere where I can see what times you did deployments?

**Comment by OriHoch** [comment]
@omerpines 
> Don't add more instances because leon is updating production and i dont want to deal with multiple instances right now. But maybe increase server?

**Comment by LeonFedotov** [comment]
yea I know - we are considering having one big server or another separated worker for the sync script, it runs on all instances now.

**Comment by OriHoch** [comment]
![image](https://cloud.githubusercontent.com/assets/1198854/26283210/eeb09ea6-3e2b-11e7-9217-da1be9abff35.png)

**Comment by OriHoch** [comment]
@LeonFedotov  / @omerpines  - if someone could explain what's the problem with many instance, that would be helpful..

I am not aware of any problems with this setup - AFAIK you can add more instances, that's the best solution

having one big server is not a good idea IMO..

**Comment by OriHoch** [comment]
also, I'm not familiar with the sync scripts, if you could link to some details that will be helpful

I'll wait for some more details before continuing work on this issue..

**Comment by LeonFedotov** [comment]
@OriHoch https://github.com/Midburn/Spark/blob/master/app.js#L260

**Comment by OriHoch** [comment]
thanks, looks like this is the culprit :+1: 

opened #436 to move it to a cronjob

**Comment by OriHoch** [comment]
will wait for #436 to be deployed, then check the latency again

**Comment by OriHoch** [comment]
looks good for now, will check again tomorrow

**Comment by OriHoch** [comment]
still spiking... :( will continue to investigate
![image](https://cloud.githubusercontent.com/assets/1198854/26326738/400d35d8-3f45-11e7-9753-43bc9573f9f0.png)

**Comment by LeonFedotov** [comment]
@OriHoch any news?

**Comment by amotenko** [comment]
I guess not relevant anymore
