### ISSUE TITLE
move drupal ticket sync script to cronjob, independent of node app

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#436]
drupal sync script is run every X minutes from the node app

node is single threaded, so the entire web-app is not responsive for the time this sync script is running

this is the probable cause for latency spikes (see #435)

we should instead run this sync script on an independent cron job, and maybe also run it from a single instance only

the magic happens here:
https://github.com/Midburn/Spark/blob/master/app.js#L260
```js
if (process.env.DRUPAL_TICKET_SYNC_EVERY_X_MINUTES) {
    log.info("Drupal ticket sync is on. Sync will run every X minutes: ", process.env.DRUPAL_TICKET_SYNC_EVERY_X_MINUTES);
    setTimeout(() => {
        var drupalTicketSync = require('./scripts/drupal_ticket_sync');
        drupalTicketSync.runSyncTicketsLoop(process.env.DRUPAL_TICKET_SYNC_EVERY_X_MINUTES);
    }, 10000);
}
else {
    log.warn("Drupal ticket sync is disabled. To run, set DRUPAL_TICKET_SYNC_EVERY_X_MINUTES in your .env file")
}
```

**Comment by LeonFedotov** [comment]
I think we should have another cronjob worker that deplyes together with web but doesnt auto scale

**Comment by OriHoch** [comment]
makes sense, cool, I'll do it

**Comment by OriHoch** [comment]
Yuval Reut [2:30 PM] 
the additional problem is that it runs on both servers

Ori Hoch [2:30 PM] 
I don't think it's that big of a problem.. there is almost no CPU usage on the servers

[2:30] 
the servers are not under any load, it's just that node APP is not responsive while the sync is running

Yuval Reut [2:31 PM] 
Leon said it could create sync problms becuase both the servers are working together

[2:31] 
I was thinking to move it to a docker container and run on ECS

Ori Hoch [2:31 PM] 
I see, ok, I'll add a separate worker instance

Yuval Reut [2:31 PM] 
or soemthing like that

Ori Hoch [2:31 PM] 
yes, docker would be good.. but I can quickly do the fixes on current infrastructure

Yuval Reut [2:32 PM] 
what weer you thinking ?

Ori Hoch [2:32 PM] 
use the current AWS launch configurations and auto scaling group

[2:32] 
and AMI..

Yuval Reut [2:32 PM] 
and what make a cron job ?

Ori Hoch [2:32 PM] 
I will have a parameter in the launch configuration that indicates for an instance that it's a worker

Yuval Reut [2:33 PM] 
not following you will launch 3 machines not 2 like now

Ori Hoch [2:33 PM] 
then, you have 2 launch configurations, one for worker and one for web-app
and 2 corresponding auto-scaling group

Yuval Reut [2:33 PM] 
1 will be a worker

[2:33] 
ahh ok

[2:33] 
gotcha

Ori Hoch [2:33 PM] 
it's a bit more work in deployment, but it will work and I can do it quickly..

Yuval Reut [2:33 PM] 
so move it off to a completely separate on e

[2:34] 
we need to monitor it though somehow

[2:34] 
because if ti’s down we won’t know

Ori Hoch [2:34 PM] 
you will have 2 autoscaling groups
the existing spark-production group with 2 web-app instaqnces
and another spark-production-worker group with 1 t2.micro instance for the sync script

Yuval Reut [2:34 PM] 
I don’t think we are really touching that script so we won’ treally need to deploy so often

Ori Hoch [2:34 PM] 
yes, if you don't make changes to it, you can only deploy the regular group

Yuval Reut [2:34 PM] 
yeah

[2:35] 
so it’s not really complicating

**Comment by LeonFedotov** [comment]
@OriHoch yep thats a good idea, well need to deploy two auto scaling groups on the same binary with different start scripts...

**Comment by OriHoch** [comment]
no changes were needed to the code..

I added a `spark-production-worker` autoscaling group, currently 0 instances (as sync is still running on other instances)

here is how to deploy it, @LeonFedotov  - you can combine with your next deploy

first, deploy the web-app, to disable sync:
* duplicate the latest launch configuration (at time of writing - `spark-production-v2.5.8 (leon)`)
* modify the DEPLOYMENT_PACKAGE_URL, as you would normally to latest package url
* set `DRUPAL_TICKET_SYNC_EVERY_X_MINUTES=` - so so the sync will be disabled
* do the add / remove instances game in auto scaling group
* now, you have the web-app instances all running without sync

now, launch the worker autoscaling group
* duplicate the latest spark production worker launch configuration (at time of writing - `spark-production-v2.5.8-worker (Ori - t2.nano)`)
* modify the DEPLOYMENT_PACKAGE_URL to latest package url
* ensure `DRUPAL_TICKET_SYNC_EVERY_X_MINUTES=2`
* edit the `spark-production-worker` autoscaling group, and set to 1 instance

**Comment by LeonFedotov** [comment]
great thank you Ori!

**Comment by LeonFedotov** [comment]
lets update some doc file with this info and close this issue

**Comment by OriHoch** [comment]
I'll update the deployment docs

**Comment by OriHoch** [comment]
64f045be1c1428732cb1290a7891d298e341ef7f
