### ISSUE TITLE
Add columns to user model

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#44]
### Overview of the problem
User model should have the following columns:

- early arrivals (boolean)
- has ticket (boolean)
- TBA

According to the specs http://prnt.sc/dhnlzl

**Comment by OriHoch** [comment]
I think there is a relation, or at least a constraint in DB..

https://github.com/Midburn/Spark/blob/master/migrations/20170113114610_constraints.js

or did you mean something else?

**Comment by netanelben** [comment]
Awesome.
I'll update the issue demands.
