### ISSUE TITLE
#Camps #Gate flow fixes

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#443]
## Camps Improvement and urgent bug fixes
- [ ] Disable add/remove/delete groups members after user has ticket registered. The member nor the group admin, will not have rights to change the camp member.
- [ ] QA Security check for roles: Camps_Admin, Art_Installations_admin, prod_deps_admin. To check if every role has access to his own tab. Also, need to change permission to each group.
- [ ] Create check-boxes to disable/enable groups(camps) system.
1. Disable/Enable the option to add/change groups members.
2. Disable/Enable the option to allow join camp system. 
3. Disable/Enable the option for join, open status, closed status join.
- [ ] On members list , we need to add force approve for roles camp_admin or admin. This is when we want to add user to group and automatic approve him. This option should only be for users exists on db.
- [ ] Update the hebrew/english language strings for group type art_installation, prod_dep. If we have generic key, we will use the original one (without the t_prefix key)
- [ ] On admin index , we need to show on the group list the amount of tickets, approved members, and how many are inside the event.
- [ ] On member list, we need to show status if the user already had his ticket been ticketed. 

## Gate improvements
- [ ] The gate allow to let users with any users_groups_membership.status to enter. The only approved status: approved , approved_mgr

**Comment by amotenko** [comment]
I guess it's done, right
