### ISSUE TITLE
reduce AWS costs - shutdown / reduce servers and services to a minimum

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#458]
midburn have too much costs on AWS, need to reduce

can reduce spark to a minimal configuration of all on 1 server

also, possibly there are unused instances which can simply be shut-down

**Comment by OriHoch** [comment]
done:

* stopped some old / unused instances
* reduced spark instances to 1
* stopped the drupal sync (spark worker instance)

**Comment by omerpines** [comment]
@OriHoch , please return the drupal sync. It is not something that can we can do without if we want spark.

**Comment by OriHoch** [comment]
drupal sync is back but it's a click of a button to start or stop it - is there a reason it should run all the time? what is spark being used for now?
