### ISSUE TITLE
Update spark for incoming sandbox gate use

### ISSUE THREAD

**Issue by LeonFedotov** [Midburn/spark#462]
Hi, iv'e been looking into what we need to change to make spark and especially the gate switch using the sandbox tickets, here's the places ive found require a change.
DB: under the events table we should change the event name code to the current sandbox code, @omerpines what is it?
https://github.com/Midburn/Spark/blob/master/models/constants.js#L81
https://github.com/Midburn/Spark/blob/master/models/constants.js#L99
https://github.com/Midburn/Spark/blob/master/models/camp.js#L37
https://github.com/Midburn/Spark/blob/master/scripts/drupal_ticket_sync.js
https://github.com/Midburn/Spark/blob/master/routes/api_camps_routes.js#L921

@roy-zahor & @asihud am im missing something? i would really use a second eye :) 
cheers!

**Comment by omerpines** [comment]
Event ID: 40
Tickets ID: 49-52

**Comment by LeonFedotov** [comment]
> [13:02, 10/5/2017] Omer Pines: לאון, צרפתי פה את אסי.
> אסי אומר שתשנה בקבצי הconstant והsync.
> 1. כל הכרטיסים הם type adult
> 2. 4 Ticket ids i sent you.
> 3. Change anywhere that's written MIDBURN2017 to SANDBOX2017.
> [13:04, 10/5/2017] Omer Pines: 4. In the gate web app and scanning mobile app, We need to the block option to leave and re-enter after ticket changes status to Entered.
> [13:04, 10/5/2017] Omer Pines: I think @Roy Zahor  prepared a flag for this.
> [13:05, 10/5/2017] Omer Pines: After you commit and deploy, we need to QA the shit out of it.

**Comment by asihud** [comment]
@LeonFedotov , exactly , those files should be changed.

just not to forget to update the models/constants.js

const ticketType = {
    SUPPORT_TICKET: '39',
    ADULT_TICKET: '40',
    CHILD_TICKET: '41',
    ADULT_DIRECT_SALE_TICKET: '43',
    YOUTH_TICKET: '44',
    LOW_INCOME_TICKET: '45',
    INTERNATIONAL_DIRECT_SALE: '46'

    // ADD HERE THE NEW TICKET TYPES:
    SANDBOX2017_ADULT_TICKET: '49',
    ... all tickets


};

// TODO We should not use enums like this at all!! Add ticket_types table to DB
const events = {
    MIDBURN2017: {
        bundles: [
            ticketType.SUPPORT_TICKET,
            ticketType.ADULT_TICKET,
            ticketType.CHILD_TICKET,
            ticketType.ADULT_DIRECT_SALE_TICKET,
            ticketType.YOUTH_TICKET,
            ticketType.LOW_INCOME_TICKET,
            ticketType.INTERNATIONAL_DIRECT_SALE
        ]
    },
    SANDBOX2017: {
        bundles: [
             ticketType.SANDBOX2017_ADULT_TICKET,
            // add here all types
        ]
    }
};

once the current event_id will be switched to SANDBOX2017, 
and all places we replace MIDBURN2017 with SANDBOX2017 (except places like constants.js), it should be working.

**Comment by amotenko** [comment]
almost done reverting all the nastiness ;)

**Comment by LeonFedotov** [comment]
@amotenko good job :)
