### ISSUE TITLE
Split README to CONTRIBUTING file

### ISSUE THREAD

**Issue by kaplanlior** [Midburn/spark#472]
README - Info about the project, what is it used for, how is it build (key components) and how to use it.
CONTRIBUTING - How to setup dev environment, how to contribute code (e.g. bugs, what branch to use, which tests to run, etc) and what is the road map for the project.

**Comment by amotenko** [comment]
https://github.com/Midburn/spark/blob/master/CONTRIBUTING.md
https://github.com/Midburn/spark/blob/master/README.md
