### ISSUE TITLE
Events Main edit form /pages/events/edit.jade with properties

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#474]
This is the main form to create a new event or edit existing event.

- [x] Edit the event files and front end to have an editor of properties:
    - **event_id** [string - string(15)] The event_id reference
    - **lastyear_event_id** [string - string(15)] The event_id of the last year, for copying things.
    - **start_datetime** [datetime - date/time] event start date and time
    - **end_datetime** [datetime - date/time] event end date and time.
    - **start_presale**_tickets [datetime - date/time] presale ticket phase start and end time.    
      This should be the pre_sale phase, where communities get quota and point thier members.
    - end_presale_tickets [datetime - date/time] 
    - **community_camps** [checkbox - boolean] event Theme Camp  Community enabled/disabled.
    - **community_art_installation** [checkbox] event Art Installation  Community enabled/disabled.
    - **community_prod_dep** [checkbox] event Production Departments Community enabled/disabled.
    - **tickets_info** [text] event tickets text-should be json text 
    - **desc_he** [text - string] event description
    - **url** string [input ] The event main URL page

- [x] Create new event or edit exists events.
- [x] Once event is started, both the start date and end date , are disabled for edit.
- [x] The Form will start with a list of all events, and edit button. index-admin page.
- [ ] Selecting the Default event_id, this parameter should be global

* Note: the current_event_id and all current_event_id properties should be loaded as global variables, to be available on all application.
* Note2: the current_event_id is a session variable of logged user. as he can switch between available events.
* Note3: - Create a camp api call to copy from old event id, for communities, and reset their counters moved to #496

**Comment by yaniv-peretz** [comment]
- [X]  Edit the event files and front end to have an editor of properties

* still need to connect the 'create new event' and 'cancel' to and data model (such as angular model), 
and set to an post/put API.
* the post/put api is not created yet.

**Comment by asihud** [comment]
@Yanipo5 @ArtyomKa 
Can we make sure the event can be created correct, and small issues at last meeting should be setup.
as well, as needed to:

**Comment by ArtyomKa** [comment]
I'm attending the Burnerot this weekend so I won't be able to help. @Yanipo5 can definitely handle the server side also if he is available. If not, we will finish it during the next meeting.

**Comment by yaniv-peretz** [comment]
merged updates: creation and edit of events now saves to the DB (all fields).

Note:
Shold "מזהה אירוע קודם" point to another event ID? if so:
 it is currently set as a DB integer column, instead of String.
therefore I might need help changing the column (knex help needed).
it is mandatory field on edit.

**Comment by yaniv-peretz** [comment]
Selecting the Default event_id, this parameter should be global,
clarification? 
Is this a request for a control to change the current perspective event?
should the control be part of home/nav bar?

**Comment by yaniv-peretz** [comment]
@alechko , @guyzohar1
If I correct in both, than we could close the issue, please confirm.
- [ ] Selecting the Default event_id, this parameter should be global
We have this functionally now on the home page.
   
- [ ] Note3: Create a camp api call to copy from old event id, for communities, and reset their counters moved to #496 -
note: We decided not to do that.
