### ISSUE TITLE
Communities Pre Sale tickets creation

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#475]
On the next event (Midburn2018) there are ticket allocation for any community (Camps/Departments.. etc).
This property allow the community manager, to select who will get the Pre Sale tickets.
To achieve that:
- [x] On The Community type Admin we need to add an editable property by the name pre_allocation.
- [x] Best would be to add database property to the community table.
- [x]  On The Community edit form, to add the property, with read only.

**Comment by asihud** [comment]
@guyzohar1 , 
in this Issue, we need to do some stuff:
- [x] Editable on the communities list of the admin page.
- [x] Export to CSV of the presale members on the camp
- [x] Set up properties to be taken from the event data of pre_sale_start_date, pre_sale_end_date, and to make sure that the Pre Sale ticket selection is executed within the date.

**Comment by guyzohar1** [comment]
done
