### ISSUE TITLE
Integrate an input control for time-date on the camps form

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#476]
### Overview of the problem
On all forms, we do not have input control of type Date Time type. 

### Steps to Reproduce
- [x] On Camps /views/pages/camps/index_admin.jade we need to add this control on a form. 
- [ ] Add the javascript that create this (unless we already having class that implemented the date time control

**Comment by yaniv-peretz** [comment]
PR #559  

- [ ] Add the javascript that create this (unless we already having class that implemented the date time control
doesn't require a global function, instead it is local for the specific angular controller
