### ISSUE TITLE
Add edit field for pre_sale_tickets_quota

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#478]
- [x] On the community admin page forms (where all the communities are displayed) we need to add a column pre_sale_tickets_quota (
- [x] On the camp form this field should be added (after the early_arrival_quota). it should be read only to anyone but campsAdmin and Admins roles.
- [x] On the camp members field we need to add another column, which is checkbox and should be selected to the maximum quota available. After specific date, this checkboxed will be readonly, and will not be able to update.

**Comment by Yanipo5** [comment]
עובד על זה

**Comment by guyzohar1** [comment]
ticket is ready, pending approve
2 known issues:

1. there is no check if the user is approved in the camp
2. there is a delay when the new data is sent back from the server to the client, this means that the checkbox value has a small delay until it is updated and the manager can add another person until it os set. this can be solved by checking the actual value of the user in the scope and not using the checkbox value

**Comment by guyzohar1** [comment]
done
