### ISSUE TITLE
Travis CI build fails on deployment stage.

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#480]
### Overview of the problem
Builds on master branch fail.

### Description
After completing the testing phase, Travis CI attempts to deploy (to staging?) and fails.

### Steps to Reproduce

Run build master branch in Travis CI
### Expected behavior
New version should be deployed to the staging server

### Actual behavior
Error message:
```
ssh: connect to host 54.194.247.12 port 22: Connection timed out
```

**Comment by OriHoch** [comment]
I will be able to get to it next week, I'll try sooner, let me know if someone else makes noises of fixing it

**Comment by kaplanlior** [comment]
Is it just a connection problem to our existing server or should I ask DevOps for a new server?

**Comment by OriHoch** [comment]
This deployment system was a quick hack I did to help us get up quickly last year, it was never meant to be a long-term solution
I think we also took down some server and environments relating to spark, so some work needs to be done to get it back up

If there are other DevOps people that can do it, they are welcome, I'll only get to it around next week

**Comment by ArtyomKa** [comment]
Actually spark staging env. is down since 10/10

**Comment by OriHoch** [comment]
#471 is my long-term solution for this, hopefully will be done sooner rather then later
