### ISSUE TITLE
fix npm install warnings

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#49]
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

**Comment by OriHoch** [comment]
can see them on travis - 
https://travis-ci.org/OriHoch/Spark#L152

**Comment by netanelben** [comment]
From that list what's left is: Jade
I'll fix it.

**Comment by amotenko** [comment]
I guess it's solved now
