### ISSUE TITLE
Add breadcrumbs titles for the current event

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#494]
At the moment at any place where we have the breadcrumbs (for example: on camps_api.js)
        req.breadcrumbs([{
            name: 'breadcrumbs.home',
            url: '/' + req.params.lng + '/home'
        },
        {
            name: 'camps:breadcrumbs.manage',
            url: '/' + req.params.lng + '/camps-admin'
        },
        {
            name: 'camps:breadcrumbs.new',
            url: '/' + req.params.lng + '/camps/new/?c=' + req.query.c
        }]);
we need to add events so on every place on the web we will see:
the current event of the user is in req.user.current_event_id
and all props can be found in Events.get_event 
so the title should be looking like: HOME -> MIDBURN2017 -> CAMPS MANAGE -> EDIT

**Comment by guyzohar1** [comment]
done
