### ISSUE TITLE
Set command for get_current_event for user

### ISSUE THREAD

**Issue by asihud** [Midburn/spark#501]
when we load any data with reference to events,
(for example, the user camp list, or editing the camp),
we need to take the event_id not from the constant of current_event_id, but to take it from the user current_event_id.
for that, we will add to User object a function .get_current_event, this will return the current event (if the user has access to), and if its not available, we will set on the user record the current_event_id that fits his rights.

**Comment by asihud** [comment]
@scopsy , are you still on this issue ?

**Comment by guyzohar1** [comment]
done
