### ISSUE TITLE
bug- as a admin, i can't enter  and view a camp

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#534]
As a admin, when i click on ניהול מחנות and than try to view the camp details i'm getting an error page
![screenshot 2018-01-04 at 17 26 13](https://user-images.githubusercontent.com/34742039/34570512-aa78e50c-f174-11e7-8ada-d391753416c5.png)

I suppose to be able to see the camp details.

**Comment by guyzohar1** [comment]
fix at PR https://github.com/Midburn/spark/pull/535

**Comment by amotenko** [comment]
Solved, closing issue
