### ISSUE TITLE
bug- as a admin, i can't enter and view an art installation

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#538]
As a admin, when i click on ניהול מיצבים and than try to view the camp details i'm getting an error page
![screenshot 2018-01-05 at 17 42 59](https://user-images.githubusercontent.com/34742039/34616153-f2088ea6-f23f-11e7-96c1-681cec6eda46.png)
I suppose to be able to see the art intallation details.

**Comment by ArtyomKa** [comment]
Hmmm. Well the problem is that we are trying to fetch from the BD a _camp_ instead of an _art_installation_.
Does any one have an idea why we even have this constraint? @asihud ? 
I'm talking about line 29 in [camps_routes.js](https://github.com/Midburn/spark/blob/master/routes/camps_routes.js#L29)

**Comment by ghost** [comment]
I was just talking to @guyzohar about this. 

The only reason I can think of is if different data/view is implemented for each type. 

For example, camps have members. Do art installations have members as well?

The options I see are:
1. If they are all the same, remove the filter
2. If they are different, create a specific method to display/update/create/etc each

We might even want to separate them into different files and not have everything in camps _routes.js

**Comment by ArtyomKa** [comment]
art installations have members (burners that help to build them).
 I removed the filter, and merged. It does not crash anymore.
last year art installation managers did not use spark, so I'm not sure what was implemented or what the requirements were. Anyway, Let's receive as much input from the QA team and then I hope we will be able to  suggest solutions and prioritize fixes.
