### ISSUE TITLE
Camps website should have a dedicated welcome screen

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#54]
**Camps module**

Welcome screen to Camps should not read 

![image](https://cloud.githubusercontent.com/assets/172282/22289348/be889ed2-e303-11e6-9509-dfb25b95e868.png)

but rather show a dedicate screen with different text.

**Comment by ripper234** [comment]
The <title> should also read "Midburn Theme Camps" and not "Spark by Midburn"

**Comment by asihud** [comment]
in this feature, I want that if the logged user has role of camp manager,
the tab of camps will be opened by default.
