### ISSUE TITLE
Can't mark  a camp member to give him a ticket although the camp have tickets

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#541]
Under עריכת חברים when i try to mark someone to give him a ticket אשר כרטיס במכירה מוקדמת the option is locked although the camp have tickets in the bucket.

**Comment by yaniv-peretz** [comment]
Hi,
are you using the button on the side?
logged as admin\campadmin, and with valid presale allocation dates?
recommend testing on the presale-allocation-date-control branch as well

![image](https://user-images.githubusercontent.com/29729128/34649623-a69a3b7c-f3bb-11e7-8d5c-a1e060d98367.png)

**Comment by guyzohar1** [comment]
fixed
