### ISSUE TITLE
Can't register new account due to CAPTCHA on staging server

### ISSUE THREAD

**Issue by ripper234** [Midburn/spark#55]
On our staging server:

![image](https://cloud.githubusercontent.com/assets/172282/22289602/1ed632da-e305-11e6-855d-fa9ed9bbfe6c.png)

I expect the solution to include:

1. Giving the staging served a fixed URL
2. Updating that in our reCAPTCHA account

**Comment by OriHoch** [comment]
once #57 is merged this recaptcha configuration error will be ignored and will allow to continue sign-up
also added configurable recaptcha keys

**Comment by amotenko** [comment]
@ripper234 is that fixed for you?

**Comment by ripper234** [comment]
Seems fixed, yeah.
