### ISSUE TITLE
מיקום מספר הכרטיסים וכמות חברי המחנה במסך ניהול חברי מחנה

### ISSUE THREAD

**Issue by anthonymassader** [Midburn/spark#552]
### Overview of the problem

<-- This is about the Spark **Camps module** -->

### Description

להעביר מתחתית הדף לראש הדף

**Comment by pandamichal** [comment]
לשנות את הטקסט מ 
סה״כ כרטיסים במכירה מוקדמת
ל:
כמות הכרטיסים שהוקצו למכירה המוקדמת

**Comment by amotenko** [comment]
solved
