### ISSUE TITLE
4. admin cant allocate presale tickets

### ISSUE THREAD

**Issue by zenihila** [Midburn/spark#555]
admin bug 
chrome 
when i try to allocate tickets to member of art member it saysare you sure then : popup error

**Comment by yaniv-peretz** [comment]
can you please try from branch: presale-allocation-date-control?
please also check that the allocation dates are set up for the current event.

**Comment by guyzohar1** [comment]
Need to check if there was allocation to the camp
in the error message you have the information why it was rejected
I fixed all the issues related to this

**Comment by guyzohar1** [comment]
this is solved in version 2.10.13
