### ISSUE TITLE
Fix Drupal login integration to indicate types of login errors

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#569]
Drupal should give us an indication if the user can't login because of problem with terms and conditions etc . so that Spark would be able to redirect user to profile system for signing those.

**Comment by OriHoch** [comment]
I don't think we need to wait for drupal, just redirect user to profile system login in case of any login problems

the error in this case can be detected in our code, I don't think it requires any change on Drupal side

see the relevant server logs here - #549

**Comment by OriHoch** [comment]
I implemented my suggestion in this PR - #577 
opened an issue to improve the UX (after this PR is merged) - #578

**Comment by amotenko** [comment]
closing, see above issues for continuation
