### ISSUE TITLE
Clean NPM dependencies

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#574]
Remove unneeded, organize duplicates, updated outdated, replace bower with yarn.

**Comment by amotenko** [comment]
See discussion here:
https://github.com/Midburn/spark/issues/571

**Comment by ghost** [comment]
@amotenko  PR pending...

**Comment by ghost** [comment]
@amotenko I closed the PR, as it was already stale.
I'll recheck the latest branch once all the PRs are merged and I'll redo, if needed.

**Comment by yaniv-peretz** [comment]
Done
