### ISSUE TITLE
Login with an email address that has the '+' sign doesn't work

### ISSUE THREAD

**Issue by talbarda** [Midburn/spark#575]
bug

no

### Overview of the problem
My Midburn profile is talbarda88+midburn@gmail.com but I can't login with it, and I can login only with _talbarda88midburn@gmail.com_ (pay attention the second address doesn't have the '+' sign).
This could have other consequences such sending me an email to the wrong email address.

**Comment by talbarda** [comment]
![image](https://user-images.githubusercontent.com/7590174/35221589-5cbde4d0-ff83-11e7-89e9-21bac1d121d6.png)
This my real profile email (My Profile tab)
Whether, I **think** the problem is with url encoding.. look at the main screen (generated url is https://profile.midburn.org/en/users/talbarda88midburngmailcom/welcome) and the email it's generating
![image](https://user-images.githubusercontent.com/7590174/35221648-95ace160-ff83-11e7-9afa-3aa88a9ee61e.png)

**Comment by amotenko** [comment]
@talbarda we'll test the fix as soon as our env is stable
