### ISSUE TITLE
improve UX of error message displayed when user needs to complete details in drupal

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#578]
## reproduction steps
* have user which didn't complete all required details in their drupal midburn profile
* login to spark

#### expected
* show nice popup / page that explains to the user that they need to go to drupal and do a login there and then return to spark

#### actual
(after PR #577 is merged)
![image](https://user-images.githubusercontent.com/1198854/34974515-23ba5b10-fa96-11e7-80ab-39e9f0d50126.png)

**Comment by OriHoch** [comment]
it can be hard to reproduce this issue, I suggest to just write some code that will fake this error

e.g. [here](https://github.com/OriHoch/Spark/blob/fix-bad-gateway-bug-due-to-drupal-missing-checkbox/libs/passport.js#L69) - change to `if(true)` to always cause this error

**Comment by amotenko** [comment]
I think it's good enough. We could also redirect users, maybe next year
