### ISSUE TITLE
Seed data and dummy data

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#585]
Spark should have a mechanism for generating quality dummy data on staging environment (think QA),
as well as having good seeding data (think development and testing).

See discussion here:
https://github.com/Midburn/spark/issues/571

**Comment by OriHoch** [comment]
another option is to sanitize DB data from production

you could have a white-list of allowed tables, columns and where conditions

then it's just a simple script which fetches only those details periodically from production

once you have this sanitized SQL dump we could create a docker DB container preloaded with this data (like we have for Drupal)

**Comment by OriHoch** [comment]
in this method, you would have all the public details (like camps lists, department names, general configurations etc..) and private details could be filled-in manually or filtered for allowed details..

**Comment by OriHoch** [comment]
related K8S issue: https://github.com/Midburn/midburn-k8s/issues/11

**Comment by amotenko** [comment]
So the thing is that it's not just about user privacy, it's also about consistency.
Ideally, the state of the staging/test database should be consistent and defined as code.
What that means is that tests are able to rely on it (during integration tests) , and there is a nightly process that roles the state of the database to it's original condition (on staging).
Although those are not the same scenario I don't see a reason to separate the two, and since we need a consistent way to populate the database, this (future) solution can be used for both.

**Comment by amotenko** [comment]
We have good seed data, dummy data on staging, not so much.
Maybe next year.
