### ISSUE TITLE
Camps listing page (Admin)

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#59]
## 3-cards camp management page
1. Camps list
2. Bulk camp update
3. Global flags

### Camps list

In this page, list of all camps registered in the system

Mockup
http://prntscr.com/dhnqwl (List)

Table attributes:
- camp name
- contact person name
- contact person email
- contact person phone
- camp status
- filled activity?
- filled location info?
- filled safety check-list?

Features:
- [ ] search camp within this list
- [ ] statistic, i.e total camps, total camp-members, 

### Bulk camp update

Mockup
http://prntscr.com/dhnrg0 (Update)

### Global flags

Mockup
http://prntscr.com/dhnrn8 (Global flags)

This card has 3 options to freeze camp editing fields:
1. freeze location fields
2. freeze program fields
3. freeze all fields - cannot edit camp

**Comment by asihud** [comment]
most of the features of this was done.
on phase#2 we will add all the other information!
