### ISSUE TITLE
Adding new camps doesn't work for new event

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#599]
Might have something to do with default event ID

**Comment by ghost** [comment]
Checked it out in staging as well. Looks ok to me.

@alechko You want me to close this or do you want to verify in staging and close yourself?

**Comment by amotenko** [comment]
Thanks @elad-lachmi !
Verified and it works, closing (although as is often the case other snakes crawl out).
BTW alechko is some other unsuspecting dude, I'm amotenko ;)
