### ISSUE TITLE
should have documentation for QA / UX / product management

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#6]
personas, user stories, use-cases, goals etc.. 

This can be used by non-technical people for QA / product management  - and of course very beneficial to the developers as well

maybe you have it somewhere, in which case should a link to the relevant place..

**Comment by ripper234** [comment]
@amotenko & @mtr574 does this exist anywhere for Spark/Camps?
Should be linked to from our main documentation (Readmes).

**Comment by OriHoch** [comment]
added some stuff here - 
https://github.com/Midburn/Spark/blob/master/docs/usage/README.md

**Comment by ripper234** [comment]
LGTM. Can we close this issue for now?
