### ISSUE TITLE
Better admin panel for Event Admin

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#600]
Will include:

* Granular opening and closing of functionalities (on and off  and/or by date)
* Easy roles and permissions attribution

**Comment by amotenko** [comment]
Will support:
https://github.com/Midburn/spark/issues/586

**Comment by yaniv-peretz** [comment]
PR: https://github.com/Midburn/spark/pull/559
has date controls for appreciation tickets allocation & camp edit last date

what is meant by "Easy roles and permissions attribution"?
does in means the to give other users permissions on the event form?

**Comment by amotenko** [comment]
Yes!
Great work. What I meant by roles and permissions is that it will be possible to attribute special roles (such as camps admin, gate admin, etc) from this screen. 
This will be, in fact, the front from this issue. 
https://github.com/Midburn/spark/issues/586

On the other hand if it makes more sense from a ux perspective, might also be a separate tab.
