### ISSUE TITLE
When adding a new camp, there is a drop down menu of all users

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#609]
## to recreate:

go to camp admin -> add a new camp -> enter some name -> next

Note request that brings all users in database
(screenshot taken from staging system)

![image](https://user-images.githubusercontent.com/7461928/35870646-d75e3102-0b6a-11e8-80a2-6ee27d83d02e.png)

Also, said menu is disabled but yet clickable? wtf

## solution

field should be a simple text field that validates the profile via ajax after it has been inserted by the user and passed basic client-side input validation (e.g. looks like an email)

**Comment by amotenko** [comment]
Note, when editing an existing camp (i.e. camp with members attached to it),
drop down menu works as expected and serves only camp members

**Comment by ghost** [comment]
So what is the expected behavior for new camps?

I think we agree that the current behavior is logical, although not very user friendly. 

I would suggest that setting the camp manager can’t be done within the new camp wizard and can be done when editing the new camp, after adding at least one member.

**Comment by amotenko** [comment]
The problem is stemming from the fact that the system is abused.

Normally, what would happen is that the field would be a drop down of camp members, **and**, the person that is adding the camp is a member of the camp and its manager by default. This way it is possible to set a manager when adding a new camp.

Because the wizard was never used properly (manager of Camps department provided a list that was imported to Spark), those corners were never rounded.

So, expected behavior:

1. When adding a new camp, assign the user adding the camp to the camp by default. (Person can belong to several communities)
2. Camp manager can only be picked among camp members.
