### ISSUE TITLE
Creating new camp - error for no public_activity_area_sqm

### ISSUE THREAD

**Issue by yaniv-peretz** [Midburn/spark#615]
quite simply I don't see any field for 'public_activity_area_sqm' in the GUI, 
so anyone else receives the same issue when creating a camp? (just wondering if that only happens on my computer)
or should we add the 'public_activity_area_sqm field to the GUI?

log:
```
knex query-error: Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: '' for column 'public_activity_area_sqm' at row 1
09/02/18 03:15:16.058 INFO app.js : POST /camps/new 500 23.262 ms - 975
```

**Comment by amotenko** [comment]
Is that something that still happens?
I never experienced this

**Comment by amotenko** [comment]
non issue
