### ISSUE TITLE
has_ticket attribute for volunteers profiles api

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#623]
volunteers_routes.js contains an endpoint called `volunteers/profiles` used by Volunteers.

1. `has_ticket` attribute is Boolean (returning from user_info) but should be more descriptive. Modify or augment this attribute to contain **actual** number of tickets (in practice, 0, 1, or 2).

2. Possibly endpoint is broken and works against an incorrect event id (i.e. returns old data)

For additional info, @may-ben-arie

**Comment by ArtyomKa** [comment]
Looked into it. It appears that we don't receive tickets info on search queries, only on log-in. Possible solutions:
1 - Use data we have in spark _users_ table.
2 - Ask Drupal Alex to fix the search api. (talked to him on the phone, he is trying to figure it out)
### UPDATE 

Alex has fixed this on drupal side. Remains one problem. Drupal server is filtering tickets for current event. Which means that we will receive data only for current event and Drupal has to "know" what the current event is.
But for now it should be sufficient.

**Comment by ArtyomKa** [comment]
Fixed in #636

**Comment by amotenko** [comment]
waiting for may's input

**Comment by mbenarie** [comment]
The api works in staging, but it's still a boolean and not the exact number of tickets.
Because it's urgent i suggest to keep it like that and deploy to production.
in the meantime we can work on a new field: num_of_tickets.
so in the end will have:
{
has_ticket: true,
num_of_tickets: 2,
...
}

**Comment by ArtyomKa** [comment]
oh. I was not aware that you need the number of tickets. will fix this
today. as you suggested - leave the boolean and add the number of tickets.

**Comment by mbenarie** [comment]
yay thanks

**Comment by ArtyomKa** [comment]
Fixed (again) in #647

**Comment by may-ben-arie** [comment]
@ArtyomKa Cool, I verified the num_of_tickets works as expected in QA, and already added this info to our UI :)

**Comment by amotenko** [comment]
releasing !
