### ISSUE TITLE
Ingest camp list to Spark database 

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#624]
Because some things change slowly, we will need to import the camp list for this year directly into the database.
We will need to write an SQL script looping through the list and inserting a new camp for each row, the list is available in a csv format.

**Comment by amotenko** [comment]
and it should be easily adaptable to ingest Art installations as well.

**Comment by OriHoch** [comment]
let me know if you want me to do it / need help doing it

**Comment by amotenko** [comment]
Yes, of course. I'll forward you the details.
@ArtyomKa might have some code lying around from last time that can help.

**Comment by ArtyomKa** [comment]
I have a script that we used to set _camp_manager_ roles to a specified users. can be found [here](https://github.com/Midburn/spark/blob/master/scripts/update_art_managers_roles.js).

**Comment by OriHoch** [comment]
done on the staging database, please test

documented the method here - https://github.com/Midburn/spark/blob/master/docs/development/camps-import.MD

if there are any problems, can fix the method and re-import

**Comment by ArtyomKa** [comment]
What is the motivation for using new table for camps instead of appending the data into the existing?

**Comment by OriHoch** [comment]
@ArtyomKa the new table is only temporary, the data is appended to the existing tables

**Comment by OriHoch** [comment]
let me know if some data is missing in a column / a relation is missing and I will fix it

**Comment by amotenko** [comment]
Done
