### ISSUE TITLE
Camp type and status strings displayed raw

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#625]
As seen on home page and My Camp page

![image](https://user-images.githubusercontent.com/7461928/36122791-5aa87986-1053-11e8-846c-afbf20d53f3e.png)

![image](https://user-images.githubusercontent.com/7461928/36122855-8a5e7856-1053-11e8-8302-a8b4462b98d9.png)

**Comment by Aroundafur** [comment]
now texts are presented in english
![image](https://user-images.githubusercontent.com/5235282/36944471-9bb57832-1fa5-11e8-991a-b23e7087c1cd.png)

**Comment by Aroundafur** [comment]
@yaarams  FYI

**Comment by Aroundafur** [comment]
![image](https://user-images.githubusercontent.com/5235282/37734271-5a3e2cc6-2d53-11e8-98e8-9a6a94128f10.png)

could this be fixed? @amotenko

**Comment by amotenko** [comment]
Might have been fixed.
I still see a localisation issue in your screenshot though, since the status should also be translated.
@aroundafur

**Comment by amotenko** [comment]
solved
