### ISSUE TITLE
Configure S3 buckets for camp files on prod and stageing

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#630]
At the moment no buckets are configured for those environments since the feature wasn't operational last year.

1. Create two separate buckets on S3 for prod and staging
2. Configure those buckets in env variables

**Comment by ghost** [comment]
Done, deployed to staging and basic manual sanity test run.
Files can be uploaded, viewed (via presigned url from the client) and deleted by an admin or camp manager.
I'll open a new issue for the file management page, which will allow viewing and downloading of files for admins only.
