### ISSUE TITLE
View / Replace / Delete files uploaded by camp managers

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#631]
Once camp manager uploaded a file, he should be able to view, remove or replace the file.

**Comment by ghost** [comment]
I’ve done this, but never merged it since no one was able to review it at the time and it became unmergeable. 

I still have my original implementation. 
I can redo it.

**Comment by amotenko** [comment]
yesss

**Comment by amotenko** [comment]
related issue:
https://github.com/Midburn/spark/issues/631

**Comment by ghost** [comment]
Done  29aec1e
