### ISSUE TITLE
Ingest art installation data

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#635]
Similar to https://github.com/Midburn/spark/issues/624 but with a twist,
this time the user list is also available to us.

**Comment by OriHoch** [comment]
will try to do it in the tech meeting today

**Comment by OriHoch** [comment]
https://github.com/Midburn/spark/blob/master/docs/development/art-import.MD

**Comment by amotenko** [comment]
done

**Comment by OriHoch** [comment]
done
