### ISSUE TITLE
default event should be midburn 2018

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#646]
<p dir=rtl>
יעזור לאנשים אם הדיפולט כשנכנסים יהיה מידברן 2018 לא 2017 :)
לא יודעת אם זה פשוט ואם יש מישהו שיכול לעשות את זה...
</p>

**Comment by OriHoch** [comment]
bug report from Facebook 
https://m.facebook.com/groups/665394353497548?view=permalink&id=1626228227414151

**Comment by OriHoch** [comment]
another rightfully disgruntled user..
אני נפלתי בדיוק בגלל זה.

אז קרתה לנו תקרית קטנה ובמקום ליצור רשימה עדכנית תחת מידברן 2018, ערכנו את רשימת החברים של מידברן 2017 ועדכנו על גביה.
עכשיו הכול מושלם וקיים אבל לא במקום הנכון. 
האם יש איך לייצא את רשימת 2017 ולייבא אותה תחת רשימת 2018? חלום שלי אם כן!

#עלטעויותמשלמים?

**Comment by amotenko** [comment]
Yes, very true

**Comment by yaniv-peretz** [comment]
updating.... event ID will change to 'MIDBURN${current_yaer}'
so every year the default will change...
#666
