### ISSUE TITLE
Program page

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#65]
Backend PR: https://github.com/Midburn/Spark/pull/75

In this page you create a program schedule of your camp, activities, parties, lectures etc..

Follow this: 
1. http://prntscr.com/dhnir4
2. http://prntscr.com/dhnj9l

**Comment by netanelben** [comment]
COPIED FROM ASANA:


Guy Warburg | 25-Jan at 3:24pm
1
Completed client-side work.
Branch includes:
- new web page for submitting a new program.
- i18n files for both he and en
- css improvements
- js data-parsing and ajax post request.

tmp additions:
- link from home page to program page for testing.
- routing for link.
- api routing to accept post request.

Bugs:
- I used 'MultiSelector' to create check-boxes and it doesn't support i18n - need to solve issue.

**Comment by asihud** [comment]
@mtr574 
where do we want to save the program data ? new table ? json data on camps ?
do we have the gui forms ready ?

**Comment by amotenko** [comment]
This should be part of a broader Playinfo system. See current and previous projects:

https://github.com/Midburn/midburn-mobile

https://github.com/kaplanlior/playainfo
