### ISSUE TITLE
[facebook bugs] wierd problems on login

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#653]
**all from ~24 hours around Feb 21**
<hr/>
<p dir=rtl>
לעוד מישהו/י הספארק לא עובד לחברי הקמפ שמנסים להירשם? הם אישרו תקנון בפרופיל מידברן ועדיין זה לא עובד... באג?
</p>
<hr/>
<p dir=rtl>
. יש סיכוי שעדיין יש באג ברגע זה בגלל עומס? חברי המחנה שלי מנסים להירשם ולא מצליחים
</p>
<hr/>
<p dir=rtl>
חברי המחנה שלי מאשרים תקנון, ואז נכנסים לספארק ולא מצליחים להירשם. עולה להם עמוד ריק של error
</p>
<hr/>
<p dir=rtl>
לי הייתה בעיה דרך המחשב אבל דרך הנייד כן עבד. שינסו
</p>
<hr/>

* maybe the bugs are related to #651 
* important to rule out any infrastructure problems.. (I fixed the spark scaling, so it shouldn't be an issue)

**Comment by OriHoch** [comment]
<hr/>
<p dir=rtl>
 בינתיים חלק מצליחים וחלק לא.. תודה
</p>
<hr/>

**Comment by OriHoch** [comment]
<hr/>
<p>
מחר יום אחרון להגיש מחנה. הספארק תקוע
</p>
<hr/>

**Comment by yaniv-peretz** [comment]
לא כל כך ברור מה לא עובד?
האם זה ה
Login?
כלומר לאחר אישור תקנון הם לא מצליחים להתחבר לתוך המערכת?

**Comment by OriHoch** [comment]
I wrote all complaints there, I don't have any more details

**Comment by amotenko** [comment]
non issue
