### ISSUE TITLE
[Facebook bug] change event to 2018 should work on mobile

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#662]
<hr/>
<p>
תגידו, גם למישהו אחר קורה שכשנכנסים לספארק במובייל, ובוחרים את MIDBURN2018 זה לא מגיב ונשאר על MIDBURN2017? קצת בעיה.. מכיוון שיש צורך להיכנס גם בדרכים...
</p>
<hr/>

**Comment by OriHoch** [comment]
alternatively, it could be solved by making 2018 the default event

**Comment by ArtyomKa** [comment]
I had no problem changing the current event to MIDBURN2018. 
Of course making MIDBURN2018 the default event is a good idea regardless..

**Comment by amotenko** [comment]
since when are we even trying to be responsive :)
in any case ticket closed
