### ISSUE TITLE
No exit button

### ISSUE THREAD

**Issue by galnitsan** [Midburn/spark#663]
Question - why there is no exit button?

### Overview of the problem

<! This is about the Spark **Users module** >no
<! This is about the Spark **Camps module** > yes
<! My **browser** is: >chrome
<! I am sure this issue is **not a duplicate**? >not sure

### Description

<! Description of the bug, enhancement, or question >

### Steps to Reproduce

<!
1.login to spark with regular user
2. on the upper menu , press התנדבות button
3. in the התנדבות screen , there is no exit button
>

### Expected behavior

<!
![exit button](https://user-images.githubusercontent.com/20013504/36655288-6ebbd00e-1aca-11e8-80c7-4a29c49b84f9.png)
 What you expected to happen --> to have an exit button

**Comment by may-ben-arie** [comment]
@amotenko I think this bug "belongs" to us.
actually there is an exit button = the midburn logo on the upper left side, but i guess no one knows that :)
Opened an issue here: https://github.com/Midburn/Volunteers/issues/135

**Comment by amotenko** [comment]
@galnitsan , hope that helps
thanks @may-ben-arie
