### ISSUE TITLE
[Facebook bugs] assortment of strange bugs / user experience

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#665]
<hr/>
<p dir=rtl>צריך עזרה בנושא ספארק. יש למישהו נסיון עם חו"לניקים שמנסים להשתייך למחנה?
החבר'ה שלנו מחו"ל אומרים שאין להם שום אפשרות לבחור קמפ. ביקשתי שיעשו ריסטרט וינסו שוב, לא עזר:-)
יש הבדל בין פרופיל בינלאומי וישראלי? יש הבדל בlayout של הספארק ?
</p>
<hr/>
<p dir=rtl>אין לי מושג אם יש הבדל ב layout..אבל אם זה עוזר, כשהספארק באנגלית טאב ״המחנה שלי״ תורגם ל nav (לא ברור 🤣)
</p>
<hr/>
<p>🤦‍♂️
</p>
<hr/>
<p dir=rtl>לחדש סיסמא בפרופיל המידברן (אפשר לאותה סיסמא) ולאשר שם את מה שצריך ... לרוב האנשים אצלנו שנתקלו בתסמיני קדחת הספארק זאת הייתה התרופה
</p>
<hr/>
<p dir=rtl>לנו הספארק עבד רק על כרום. בדפדפנים אחרים לא הצלחנו לבחור midburn2018
</p>

**Comment by OriHoch** [comment]
<hr/>
<p dir=rtl>
אז אחרי שאני רודפת אחרי הקאמפ שלי להרשם בספארק וחופרת להם , הוצאתי היום הודעה ממש כועסת וקשוחה כי רק 12 נרשמו ומה נראה להם בכלל?!?!!?

ואז גילתי שהם פשוט נרשמו למידברן 2017 - מקסים..
מישהו יכול לנעול את הספארק מפדיחות כאלה או משהו ?😅😅
</p>
<hr/>

**Comment by OriHoch** [comment]
<p dir=rtl>חשוב!!!  📢  ⚠ 
*אשרו את עצמכם במערכת מידברן ספארק עוד היום*
אנחנו כבר הזנו אתכם, (חברי המחנה) לתוך מערכת בשם ספארק.זו מערכת שנועדה לקשר בינינו לבין מארגני המידברן מאחורי הקלעים.
על בסיס המידע המוזן אנו מקבלים מהמידברן שטח (פר אדם) מ"ר לקמפ, הקצאות לכרטיסים נוספים (יש סבב ב- 3.3) ועוד כל מיני דברים שעוד נדע עליהם בהמשך  :) בכל מקרה זה דחוף וחשוב.
בינתיים אלו הפעולות שכל אחד מכם צריך לבצע:  ⬇ 
1. היכנסו ללינק הבא: https://spark.midburn.org
2. הזינו את פרטי פרופיל המידברן שלו ולהיכנס למערכת
3. שנו את האפשרות: מידברן 2017 לאפשרות מידברן 2018 (חשוב!)
4. לחצו על ה- האפשרות "המחנה שלי" שנמצא בראש העמוד
5 לחצו: "אשר בקשה" כדי לאשר את הצטרפותכם לבעזרת השם.

וזהו אתם חברים בקמפ גם במימד הפורמלי והבירוקרטי. מזל טוב!
**אם הסתבכתם כתבו לנו

** תוספת להסבר: יש ללחוץ על כפתור התפריט בצד שמאל למעלה ורק אז יש אופציה של "המחנה שלי" המובילה לעמוד בו יש לאשר את הבקשה☝
** תוספת להסבר:
</p>
<hr/>
<p dir=rtl>למה מאשימים את האנשים והמתנדבים? גם ככה מציפים אותנו בטפסים... זה על פניו UI פשוט לא הגיוני. למה בכלל יש לאנשים אפשרות להירשם ל2017?!
</p>
<hr/>
<p dir=rtl>הקטע שזה באמת בצורה דיפולטית קופץ ל 2017 ממש דבילית,  נרשמו לי לשנה שעברה מלא סטלנים 😂
</p>
<hr/>

**Comment by pandamichal** [comment]
@amotenko  i thought the default event was set to Midburn 2018... Please let's change it. Thanks!

**Comment by amotenko** [comment]
@pandamichal indeed..

**Comment by OriHoch** [comment]
this issue is about setting the default event - #646

**Comment by amotenko** [comment]
those are good now
