### ISSUE TITLE
Test_data out of sync from node seed (running on knex:migrate that has data).

### ISSUE THREAD

**Issue by yaniv-peretz** [Midburn/spark#667]
Currently our tests are running based on data created via the knex migrate:latest, (not optimal, as this is out of sync with the node seed).
Some tests where failing because 'MIDBURN2018' was not created in the test data.
I applied a quick fix, manually creating 2018-2020.

the midburn event data are in the "20170427182849_gate_data" file.
I tried to change but got some failures, need farther checks.
```
    "create_test_db": "cross-env SPARK_DB_DBNAME=spark_test mysql -u root --protocol=tcp < migrations/create_test_db.sql && cross-env SPARK_DB_DBNAME=spark_test knex migrate:latest",
```

**Comment by amotenko** [comment]
this is good now
