### ISSUE TITLE
Sandbox for major revision

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#675]
1. We would like to test the following branch on an isolated environment that is not the regular staging environment, including a clone of staging database. 

https://github.com/Midburn/spark/pull/661

2. If possible, commits to this branch would be automatically deployed to the sandbox

3. If possible, provide easy tooling for developers to set up such sandboxes in the future

**Comment by OriHoch** [comment]
branch `api-refactor-feb-2018` is continuously deployed to sparktesting environment https://spark.testing.midburn.org/

I wrote how to do it here - https://github.com/Midburn/midburn-k8s/blob/master/charts-external/spark/README.md#starting-a-testing-environment

**Comment by amotenko** [comment]
Thanks! That's awesome.
