### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#68]
every page should implement breadcrumbs.
- https://www.npmjs.com/package/express-breadcrumbs
OR
- https://www.npmjs.com/package/express-url-breadcrumb

**Comment by netanelben** [comment]
https://github.com/Midburn/Spark/tree/kushmar-added_breadcrumbs

**Comment by natekonimbo** [comment]
@itaikushmar can you merge with master? OR if it's intimidating, do this:
 pull master and apply your changes in fresh copy.
