### ISSUE TITLE
Camp members ticket count is incorrect

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#680]
Ticket count is displayed as 1 even in cases where member has 2 tickets.

I suspect drupal API integration?

**Comment by amotenko** [comment]
@ArtyomKa is that similar to what we had with volunteers API?

**Comment by ArtyomKa** [comment]
Looked at the code. There is something called _bundles_. IIUC, each ticket type has a bundle. There is a bunch of them hard coded in [constants.js](https://github.com/Midburn/spark/blob/master/models/constants.js) file. 
1 - Need to confirm that the 2018 bundle numbers are correct
2 - Looks like _pre-sale_ tickets have bundle number 60 Needs to be added to constants,
