### ISSUE TITLE
Camps Inside Event counter displayed incorrectly

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#681]
People are displayed as though they are in the event for some reason.

I suspect it might be looking in the wrong table somehow or perhaps using wrong event id

**Comment by amotenko** [comment]
@ArtyomKa is it related to the ticket counter? You mentioned it was looking in the wrong column

**Comment by ArtyomKa** [comment]
I might be. can someone verify that the bug exists in the current version?

**Comment by ArtyomKa** [comment]
I looked into it. 
Here is what I think happened:
The script extracted all tickets from drupal that belong to MIDBURN2017 and SANDBOX2017 (the array of ticket_ids is hardcoded in the script) and stored them in the spark.tickets table under event_id MIDBURN2018. This iswhay we now have MIDBURN2018 tickets that have _inside_event_ field = 1 (they are actually 2017 or sandbox tickets)
