### ISSUE TITLE
Ticket info is stale

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#687]
Spark is getting info about tickets only when a user is logging in.
This causes a problem to camp managers that see stale information on camp members.

One possible solution is to revive the ticket_sync process that used to run last year.

**Comment by OriHoch** [comment]
ticket sync is running

**Comment by OriHoch** [comment]
I'm pretty sure I also tested it back when I setup the k8d environment

**Comment by amotenko** [comment]
Good to hear! BTW, @ArtyomKa , are child tickets counted in your fix?

**Comment by ArtyomKa** [comment]
Should be. I received the bundles list from Alex Bab

**Comment by ArtyomKa** [comment]
See #717 and #681

**Comment by amotenko** [comment]
Good, now that we fixed the script, the bundles, and event ids on tickets we are back to square one.

At the moment we don't have any 2018 ticket info in our tables, and from what I understand the script is running but it doesn't take the whole data, just the recent deltas.

Also, fascinating read from last year's issues about ticket sync mechanics and the performance hit it caused (@ArtyomKa following your question)
https://github.com/Midburn/spark/issues/436

**Comment by OriHoch** [comment]
thanks @amotenko for the summary :+1: 

I'm still reluctant to touch this script with a stick...

next week I hope I will have time to help you, either by fixing this script or implementing a simpler option directly with spark DB

**Comment by ghost** [comment]
Ticket sync process is up and running.
The number of total tickets shown on the homepage is the exact number of tickets sold so far.

There is still a UI issue, but that has nothing to do with sync.
Closing.
