### ISSUE TITLE
[facebook bugs] camps upload bugs

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#690]
**Feb 27, ~22:00**
<hr/>
<p dir=rtl>
שימו לב שימו לב - ניתן להעלות תיקי מחנה לספארק, הבאג תוקן!
</p>
<p dir=rtl>
לא הוא לא ): אצלנו לפחות 🤔
</p>
<hr/>
<p dir=rtl>
נפתר ממש עכשיו... תעשו ריפרש חזק (CTRL + F5) ותנסו שוב?
</p>
<hr/>
<p dir=rtl>
מראה לי שהוא מעלה, לוחץ שמור ואפילו מקבל את ה״כל הכבוד״ אבל איך יודעים אם זה בוצע? הקובץ אמור להיות תחת הלשונית של העלאת מסמכים או במקום אחר?
</p>
<hr/>
<p dir=rtl>
למי ששואל - זה אמור להראות ככה-
אם תקליקו על הקובץ הוא יוריד לכם אותו :)
</p>

![image](https://user-images.githubusercontent.com/1198854/36774136-7531fdb8-1c65-11e8-9bb2-f4b5d7ecc8c4.png)

<hr/>
<p dir=rtl>
Nop - there's server error
</p>

![image](https://user-images.githubusercontent.com/1198854/36774145-7f7601a2-1c65-11e8-8935-b800e5308c32.png)

<hr/>
<p dir=rtl>
לנסות בincognito
</p>
<hr/>
<p dir=rtl>
תנסו לנקות קאש או לעבוד בincognito
</p>
<hr/>
<p dir=rtl>
אי אפשר
</p>
<hr/>
<p dir=rtl>
לא מצליחה גם
</p>
<hr/>

**Feb 28, ~01:00**

<hr/>
<p dir=rtl>
עדיין לא תוקן , לא מצליח להעלות
</p>
<hr/>
<p dir=rtl>
אגב ספארק, יש לי חבריי מחנה שמנסים להיכנס לספארק עם הפרופילים שלהם ולא מצליחים (אפילו לו לפרופיל). איך אפשר לתקן את זה? למי לפנות?
</p>
<hr/>

**Feb 28, ~09:00**

<hr/>
<p dir=rtl>
לא מעלה, מה תעשו לי
</p>
<hr/>

**Comment by OriHoch** [comment]
why are we asking users to clear cache, IIRC I solved caching related problems last year

if not, let's solve them, no reason to ask people to clear the cache / refresh / use incognito

**Comment by ghost** [comment]
@OriHoch Right, no need for that. no-cache reloads and incognito are for very specific issues and we shouldn't have those in Spark right now.

I did a workaround here: 4c44ded
Will do something more permanent later today.

**Comment by OriHoch** [comment]
Some more bugs from the last 0-2 hours
<hr/>
<p dir=rtl>
Doesn't work on Chrome or on edge. I can put the name of the file and then the name vanishes.
</p>
<hr/>
<p dir=rtl>
יש לי את אותה הבעיה. ניסיתי גם באינקוגינטו ולא עובד. מה עושים?
</p>
<hr/>
<p dir=rtl>
יש לכם עדין תקלה יקרים !
גם כל מה שמילאתי במערכת ספארק על המחנה שלי נמחק לחלוטין..
מה קורה :(
</p>
<hr/>
<p dir=rtl>
נשאר לי רק עוד חו"לניק אחד אחרון לרשום לספארק והוא לא מצליח עקב באג כנראה... מה אפשר לעשות? פניתי אליכם במייל ולא קיבלתי תשובה. עדיף לפנות למח' טק?
</p>
<hr/>
<p dir=rtl>
להיות סבלנים, יש לנו מעל 40 מיילים לחזור אליהם וגם עבודה "בעולם האמיתי" שדורשת את תשומת ליבנו... כולם יקבלו תשובה בקרוב.
</p>
<hr/>
<p dir=rtl>
ואם לא עובד בכרום... אינקוניטו... ספארי... :(
</p>
<hr/>

**Comment by amotenko** [comment]
issue is solved, after we remove the workaround we will make sure it is accessible to members with the right permissions.
