### ISSUE TITLE
Camps new camp wizard - errors displayed

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#692]
new camp id is not 'undefined' which throws errors

**Comment by amotenko** [comment]
https://github.com/Midburn/spark/pull/691/

**Comment by amotenko** [comment]
also @Aroundafur is on it, 
@Aroundafur please approve invitation to org so you can be assigned

**Comment by Aroundafur** [comment]
https://github.com/Midburn/spark/pull/698
