### ISSUE TITLE
Camp list interface to Website

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#696]
Although this is more to do with the website, since this is an integration with our data via our API I'm documenting this here. At the moment there are some discrepancies between the data displayed on the website and data in Spark

Desired behavior as follows:

* Camp managers can set camp as `open` or `closed` to new members
* Camp managers can set camp as `published` or `not published` to appear on the midburn website

The two settings are unrelated.

Camps that are not published will not appear in the list at all
Camps that are closed to new members will not have contact information displayed.

**Comment by amotenko** [comment]
@OriHoch

**Comment by OriHoch** [comment]
this is the relevant repo - https://github.com/Midburn/camps_index

the list is not updated automatically with spark at the moment, I will try to do it this week

**Comment by OriHoch** [comment]
done in [camps index v1.3.0](https://github.com/Midburn/camps_index/releases/tag/v1.3.0), automatically updated from spark every 10 minutes, continuously deployed to https://production.midburn.org/camps-2018/
