### ISSUE TITLE
Disappearing data from camps

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#697]
Some camps complain they had entered that is now gone.
I suspect it might have been removed when we did the second round of camp insertion.

camps for example
זקני השבט
עדן בן זקאמפ

If possible we might look at a backup and restore their info

**Comment by amotenko** [comment]
@OriHoch

**Comment by OriHoch** [comment]
all members registered to 2017 event

**Comment by yaniv-peretz** [comment]
:)
Probably related to setting a new default event.
Auto logging into 2018 now instead of 2017.

**Comment by OriHoch** [comment]
another complaint about disappearing members (camp id 1879)
<hr/>
<p dir=rtl>
אהההה!!!!! בניסיון למצא את הדרך לפרסם את המחנה לחצתי על הכפתור "פרסם" ועכשיו כל חברי המחנה נמחקו!!! האאאאא!!!!! האם אני בהריון?????!?!?!?!
</p><p dir=rtl>
מיותר כמובן לציין שהקמפ עדיין!!! מופיע כ "לא מפורסם" .. שזה בעצם מפורסם אבל בלי פרטי הקשר למצטרפים חדשים.....
</p>
<hr/>

**Comment by OriHoch** [comment]
<hr/>
<p dir=rtl>
גם המחנה שלי התפוגג לגמרי...
</p>
<hr/>

**Comment by OriHoch** [comment]
Looks like camp members data is intact, so members are not lost

**Comment by amotenko** [comment]
not an issue
