### ISSUE TITLE
project should have release tracking

### ISSUE THREAD

**Issue by OriHoch** [Midburn/spark#7]
should have release tracking, each release should have release notes - so that people can track the project progress and know what was deployed and what changes are introduced..

natural choice is to use GitHub releases..

**Comment by OriHoch** [comment]
see for example release tracking of Open Knesset - https://github.com/hasadna/Open-Knesset/releases

**Comment by ripper234** [comment]
+1 for Github releases.

(right now we haven't released any versions yet, I'm wondering whether this issue is premature / can we make progress on it right now)

**Comment by OriHoch** [comment]
The idea is to update the release notes on every merge. Can also include deployment / testing notes.

I'll write some documentation for how to do release management and we could discuss further there..

Amyway, I see someone created the first release so I'll close this issue
