### ISSUE TITLE
Free text tags of camps show code in the camp page [Bug] [Front End]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#713]
The Problem:
Free text tags of camps show code in the camp page

Steps:
1. Go to stage spark page 
https://spark.staging.midburn.org/he/login?r=/
2. login using 'Camp manager' profile:
midqacamp@gmail.com
Pass: qa123456
3. click on menu > my camp > edit camp (or the following link:)
https://spark.staging.midburn.org/he/camps/2045/edit
4. Click on 'פרטים בסיסיים' 
5. under גיפט המחנה'' mark V on other and enter free text (like 'סבבה')
6. go back to camp view page

Result:
We see code where the free text tag is shown

Expected:
please show only the free text, without the code
see screenshot

![image](https://user-images.githubusercontent.com/13450170/36951704-5c3d1c72-200f-11e8-88bf-7f314e63da3f.png)

**Comment by amotenko** [comment]
Solved in https://github.com/Midburn/spark/pull/736
