### ISSUE TITLE
tickets table has incorrect event_id

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#717]
### Overview of the problem
_tickets_ in spark database have incorrect   _event_id_ values. This is what causes the incorrect _inside_event_ data to appear in the camp memebers dialog. See: #681 

### Description
Probably caused by buggy _drupal_sync_ script. After the _event_id_ constant was changed to MIDBURN2018 old tickets where also set to this value because the TICKETS_TYPE_IDS constant was incorrect. 
1 - Existing data should be fixed (or discarded?)
2 - Drupal sync shlould be fixed to use EVENT_ID and TICKETS_TYPE_IDS from the [_models/constants.js_](https://github.com/Midburn/spark/blob/master/models/constants.js) file

**Comment by ArtyomKa** [comment]
@OriHoch Mentioned that there is another way to import tickets data from drupal. This might more elegant solution.

**Comment by ghost** [comment]
Fixed event_id according to the ticket type.
Each ticket now has the correct event_id.
