### ISSUE TITLE
Ingest ticket sale data for Art department

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#721]
In preparation for the sale next week, we need to enter the number of tickets that each art project manager can distribute to his team. 

Very similar to what we did with the previous participation sale.

Let me know that you take this and I'll send you the data

**Comment by OriHoch** [comment]
please send me the data..

**Comment by amotenko** [comment]
Shared (tab titled SPARK).
I expect there are going to be a lot of mismatches, between art installation names, emails, etc, so it would be very valuable to validate the emails as valid spark users, and have a list of rejects

**Comment by OriHoch** [comment]
done, see details in PR #724
