### ISSUE TITLE
Camps are locked for editing

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#725]
On production server, camps are locked for editing even though they are not configured to be locked in the event's admin page.

**Comment by amotenko** [comment]
Seems the MySQL server is stuck or something judging by the ER_LOCK_WAIT_TIMEOUT that returns

**Comment by amotenko** [comment]
Staging works as expected

**Comment by OriHoch** [comment]
please provide clear reproduction steps, I'm not sure how to reproduce it

in any case, I recreated the DB, so it should fix it in case there were any locks

**Comment by amotenko** [comment]
Fixed, closing
