### ISSUE TITLE
Ingest ticket sale data for Camps department

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#730]
Similar to #721 , but for camps.

If you take this let me know and I'll send you the list

**Comment by OriHoch** [comment]
I can do it tonight

**Comment by amotenko** [comment]
Sending you the info

**Comment by OriHoch** [comment]
done on production DB @amotenko @pandamichal

**Comment by OriHoch** [comment]
[metabase dashboard showing the camps pre sale tickets quotas](https://production.midburn.org/metabase/dashboard/3)

**Comment by amotenko** [comment]
done
