### ISSUE TITLE
Getting statistics from spark database (for the gate)

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#731]
The gate department needs to know the statistics of how many people entered the gate throughout the event last year. They need the number of people passed through the gate each hour.

**Comment by amotenko** [comment]
If I remember correctly this data was overrun at this year's sandbox, and we didn't have a backup of our database between midburn 17 and the sandbox

**Comment by pandamichal** [comment]
@amotenko Can we check it out? @OriHoch  maybe?

**Comment by OriHoch** [comment]
yes, looks like this data is not available in spark

it should be available in Drupal, Hila can do it, and anyone who knows SQL can try to get this data from Drupal using Metabase

**Comment by amotenko** [comment]
Was ticketing data synced back to drupal? I thought those tables were specific to Spark

**Comment by OriHoch** [comment]
I don't know..

**Comment by amotenko** [comment]
so Hila can check, and if not, sadly we don't have it.

**Comment by pandamichal** [comment]
checking with her...

**Comment by amotenko** [comment]
closing :(
