### ISSUE TITLE
Vanity issue for Leon

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#738]
I hereby confirm that @LeonFedotov has communicated with me over a popular instant messaging platform and in the span of a few short text messages, using his knowledge, experience, and expertise, helped to resolve an acute issue, thus proving his proficiency as a software engineer and value to the burner community.

**Comment by amotenko** [comment]
Issue deemed closed.

**Comment by LeonFedotov** [comment]
pfffttt @amotenko 💃 💃 💃 💃 💃
