### ISSUE TITLE
Published camps list for website

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#74]
## This page is index of published camps, for the community, will be presented in midburn.org website.

last year's page: http://midburn-themecamps.herokuapp.com/published-camps

[This task has its own repo, here](https://github.com/Midburn/camps_index)

Two main task, Front & Back end.

### Back-end task
1. [x] Create end-point with public camps;
 - end-point address: ``/camps_public``
 - response with JSON of camps with ``enabled = 1``

Details for each camp should follow these attributes,
__output two versions, english & hebrew__

1. שם בעברית, שם באנגלית
2. תיאור עברית, תיאור אנגלית
3. האם המחנה פתוח לחברים חדשים - כן/לא
4. האם המחנה מקבל משפחות - כן/לא
5. פרטים ליצירת קשר: (זה לא מנהל המחנה)
- שם פרטי ומשפחה (עברית ואנגלית)
- טלפון
- אימייל
- פייסבוק

### Front-end task
2. [x] Page to show the public camp available
 - should implement with Angular1
 - will be showen in Midburn website.

**Comment by OriHoch** [comment]
@mtr574  - could you provide more details about this public page? is it also part of spark node webapp? is it expected to be put somewhere else?

**Comment by guywarburg** [comment]
I'll take the Front-End part

**Comment by netanelben** [comment]
starting back end task

**Comment by guywarburg** [comment]
@natekonimbo can we close this task?

**Comment by asihud** [comment]
yes. this task is done, 
except that the json is not implemented.
