### ISSUE TITLE
ID number length

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#743]
At the moment we have a weird constraint that is messing with some users that ID numbers are supposed to be 9 digits long. This is not always correct.

Provide better constraints for ID number.

**Comment by ArtyomKa** [comment]
Nothing weird about 9 digits length constraint. Just should pad it with zeros.

**Comment by amotenko** [comment]
passports numbers, foreign ids, those might be longer than 9 digits, I don't think we need to have any constraint on that, we don't even use it as a unique identifier

**Comment by amotenko** [comment]
do we still have this constraint?

**Comment by yprez** [comment]
it's defined as a `varchar(9)`, 20 chars should do it, right?

**Comment by amotenko** [comment]
yup, should do.
When, if, Spark becomes the user management platform, we can rethink everything about user data.

**Comment by amotenko** [comment]
fixed
