### ISSUE TITLE
Art department - member confirmation 

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#748]
When adding a new member to an art project, member doesn't need to confirm his participation.

(from @pandamichal)

**Comment by amotenko** [comment]
Question:
How to handle cases when person doesn't want to be included in project (for example wrong user added by mistake)

**Comment by ArtyomKa** [comment]
From what i saw yesterday, we can make art installation members assignment
process to be same as theme camps. it is juat configuration issue

**Comment by amotenko** [comment]
This whole flow needs to be redesigned, the user experience is horrible.
But OK! let's get those two aligned together first.

**Comment by pandamichal** [comment]
Let's wait with that...don't apply it in this sale...people will not understand what to do.

**Comment by amotenko** [comment]
No merges until after the sale

**Comment by amotenko** [comment]
done (sorry don't remember the pr)
