### ISSUE TITLE
Only one manager per camp/art should be allowed

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#753]
At the moment more than one member can be designated as a manager which is not desirable.

(from @pandamichal)

**Comment by amotenko** [comment]
There should be a separation between the role of a manager and the privileges of a manager.
It makes sense that more than one person in a camp/art can have those privileges

**Comment by pandamichal** [comment]
I think that tickets wise- only one member could be the manager. At this moment Spark is giving mainly tickets solutions and i think only one person should have the privilege to give them.

**Comment by amotenko** [comment]
I understand the concern, but I'm reluctant to agree.
What usually happens, in a situation where a manager wants to share some of his workload, if he is unable to give some of his privileges to people he trusts is that he just gives them his username and password, which is far worse from information security point of view.
It's better to have in place a safe mechanism that allows that, and let the managers decide if, and who, they want to trust.

**Comment by ghost** [comment]
Agree completely with what Alex said. 

From experience, if there isn’t an applicative way of sharing access, usernames and passwords start making the rounds between users, which is a loss for everyone. 

I think we should support this, while keeping responsibility with the camp manager and having them as the single point of contact.

**Comment by pandamichal** [comment]
All you said is true...I think Adir-theme camps leader should decide in that manner because he is the one that deals with the lists and the managers.

**Comment by MidburnThemeCamps** [comment]
Completely agree with Alex.
Also - another facet is adding/approving members. This can be done by more than one manager. 
Only ticketing stuff should be done by a single manager, unless he decides to appoint someone else from the camp (with said privileges) and give them access.

**Comment by pandamichal** [comment]
That was my thought..that tickets should be handled by one person only. I think that adding another member that can give tickets should be by admin from theme camp and not by the camp manager.
Adir- what do you think?

**Comment by MidburnThemeCamps** [comment]
I'm actually OK with letting them appoint another "manager" who can give tickets. If it runs through us it's just more work for the team... I rather empower them and let them handle it themselves :)

**Comment by pandamichal** [comment]
OK! less work for us :-)

**Comment by MidburnThemeCamps** [comment]
Actually, it means we should go with Alex's suggestion of adding a feature to let a manager "appoint" other sub-managers... :)

**Comment by ghost** [comment]
I’m always for empowerment. 
A side from the warm fuzzy feeling, it’s also more scalable.

**Comment by amotenko** [comment]
this will have a proper UI when we merge the new roles & permissions.
A *single* camp managers will be able to assign and demote helpers from within the camp. 

https://github.com/Midburn/spark/pull/594
