### ISSUE TITLE
Export sale data

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#754]
In preparation for the upcoming sale we need to export the data we have on tickets allocation from camps and art.

Exported files should be separate for camps and for art.

the csv file should contain the following columns:

- Name of allocating camp/art project
- Email of ticket recipient

(@pandamichal anything else?)

**Comment by OriHoch** [comment]
I can create a metabase question which show this data, you can export to CSV from metabase

**Comment by OriHoch** [comment]
actually.. we already have this question, thanks to Hila (BI expert)

https://production.midburn.org/metabase/question/1

**Comment by OriHoch** [comment]
and we have camps data and art data here - 
https://production.midburn.org/metabase/question/10
https://production.midburn.org/metabase/question/9

**Comment by amotenko** [comment]
@OriHoch , number 9 and 10 are how many quotas each community received, right?
Number 1 is who has tickets and which, (correct me if I'm wrong).
Where do we find the allocated quotas per person for the upcoming sale? I don't think we have a question for this yet, but it certainly can be made.

**Comment by pandamichal** [comment]
@amotenko name of camp\art and email is enough. 
the camps should be downloaded today until 18:00,
Art scheduled for tomorrow 12.3 at 18:00.

Thanks!

**Comment by OriHoch** [comment]
@amotenko @pandamichal 
full list of camp and art members - https://production.midburn.org/metabase/question/15
need to join with tickets data, it could be done manually in excel, if not I can do it tomorrow

**Comment by amotenko** [comment]
@OriHoch thank you,
but this is not exactly what needed.

If you look at `camp_members` table, you will see some users with camps associated with the current event id have under addinfo_json `{"pre_sale_ticket":"true"}`. Those are the guys we need.
If possible with separation to art and camps.

Muchas gracias!

**Comment by OriHoch** [comment]
@amotenko https://production.midburn.org/metabase/question/16

**Comment by OriHoch** [comment]
the `Camp Type` column is used to distinguish between art and camps

**Comment by OriHoch** [comment]
I added a camp type filter to the question - https://production.midburn.org/metabase/question/16

**Comment by amotenko** [comment]
Danke dir!

I see now the value that metabase has to provide and I think it's a good thing we have, so thank you for that as well.

**Comment by OriHoch** [comment]
:+1:
