### ISSUE TITLE
Art Installation managers can not change Hebrew name

### ISSUE THREAD

**Issue by ArtyomKa** [Midburn/spark#756]
A complaint received while trying to help one of the art installation managers

### Overview of the problem
Changing Art installation name does not work.

### Description
When trying to change Hebrew name (which was imported from the Dreams sys.) art inst. managers receives a message that the change was successful but refreshing the page returns the previous name.

### Expected behavior
We should either disable editing in the UI, if this is the desired solution or save the changed name to the database. Either way it is a business-rules/product decision.

**Comment by amotenko** [comment]
And the English name?

**Comment by ArtyomKa** [comment]
I think it is disabled for editing.

**Comment by amotenko** [comment]
So the two should be aligned

**Comment by amotenko** [comment]
Solved, now neither Hebrew nor English names are editable.
