### ISSUE TITLE
Roles for camp module

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#76]
# Camp manager role

1. Create user role for camp manager, follow this string that used in the DB: `camp_manager`
2. Camp members page
   - update the route to: ``/camp/:id/members``
   - manager sees camp members with full details, while user sees less details

**Comment by OriHoch** [comment]
I can do that, could you provide more details?

**Comment by OriHoch** [comment]
not sure what is needed here but we have the roles framework, you can see documentation and usage guide here:
https://github.com/Midburn/Spark/blob/master/docs/development/users-roles-and-permissions.md
