### ISSUE TITLE
As a camp manager, I Can add non existing user in profile system to a camp [Bug] [javascript]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#765]
The Problem:
As a camp manager, I Can add non existing user in profile system to a camp

Steps:
1. go to spark
https://spark.staging.midburn.org/he/login?r=/
2. login as camp manager
3. go to edit camp > Edit friends
https://spark.staging.midburn.org/he/camps/2045/edit
4. under 'add mail of midburn profile' add non existing email (ex: lala@lala.com) and click 'add member'

Result:
The member is added to the list of members in the comp (see screenshot)

Expected:
Show error msg to camp manager that this user do not have profile in midburn, something like:
'Cant add email'
'לא ניתן לצרף אימייל'

![image](https://user-images.githubusercontent.com/13450170/37311869-a0b7f67c-2651-11e8-81e3-372ac8b4bf60.png)

**Comment by yaarams** [comment]
@ozsoffy fixed

**Comment by amotenko** [comment]
closing

**Comment by ozsoffy** [comment]
Verified
Tested on staging using camp-manager.
