### ISSUE TITLE
As a camp manager (and not Art manager), I would like to not be able to add emails of members that belongs to other camps to my camp

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#766]
The Problem:
As a camp manager, I can add emails of members that belongs to other camps to my camp 

Steps:
1 go to spark
https://spark.staging.midburn.org/he/login?r=/
2. login as camp manager
3. go to edit camp > Edit friends
https://spark.staging.midburn.org/he/camps/2045/edit
4. under 'add mail of midburn profile' add existing email of member that belong to another camp
 (ex: midqaad@gmail.com belong to camp 2045 ) and click 'add member'

Result:
The member is added to the list of members in the comp (see screenshot)

Expected:
Show error msg to camp manager that this user belong to another camp and we cant add him, something like:
'This email belong to a member that belong to another camp'
'מייל זה שייך למשתמש ששייך לקמפ אחר'

Note:
please make sure this will effect 'camp mananger' only!!! and not 'Art manager' (מנהלי מיצג), as art manager do not get there ticket by number of members. 

![image](https://user-images.githubusercontent.com/13450170/37312988-e98588ac-2655-11e8-97ed-6bfe2344a71b.png)

**Comment by yaarams** [comment]
@ozsoffy please close this issue. its a non-issue.

**Comment by amotenko** [comment]
closing

**Comment by ozsoffy** [comment]
Cant reproduce
Tested on staging using camp manager.
