### ISSUE TITLE
As Admin-user, I cant add tickets from manage-camps page [Bug] [javascript]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#767]
The Problem:
As Admin-user, I cant add tickets from manage-camps page

Steps:
1 go to spark
https://spark.staging.midburn.org/he/login?r=/
2. login as Admin-user 
3. go to camp management 
https://spark.staging.midburn.org/he/camps-admin
4. Search for a camp and try to add it a tickets.

Result:
The data is not saved. (see screenshot)

Expected:
The Admin-user, can add tickets using this page, and getting a message or something that he successfully added the tickets to that camp.

Workaround:
The admin-user, can go to edit camp, and inside the edit page to add tickets to the camp.

![image](https://user-images.githubusercontent.com/13450170/37313953-258bccfe-265a-11e8-8694-e0c61b81a197.png)

**Comment by NitayRabi** [comment]
This might be resolved when https://github.com/Midburn/spark/pull/742 will be merged.

**Comment by Demikulu** [comment]
This issue is also fixed, you are welcome to close it.

**Comment by amotenko** [comment]
fixed, closing

**Comment by ozsoffy** [comment]
Verified.
Tested on Staging using Admin user.
