### ISSUE TITLE
Bug: Installation/Project Name is corrupt and wrong ("camp" 1999)

### ISSUE THREAD

**Issue by yossilan** [Midburn/spark#769]
Hi, 

I'm leading The Dimyonon installation and the project name in spark is wrong both in Hebrew and English. For some reason, I can't really edit the name in the English field and when I edit the name in the Hebrew field it keeps reverting to the corrupt version... 

The corrupt version: DREAM_he Dimyonon - An Interactive Stage/Playgroun
Should be: The Dimyonon 
Should be in Hebrew: הדמיונון 

תודה

**Comment by OriHoch** [comment]
Why do you need to edit these details?

In any case, I updated directly in DB.. let me know if it looks OK now

**Comment by yossilan** [comment]
נהדר, המון תודות!!

ניסיתי לערוך את שם הפרויקט מכיוון שבצורה שזה היה כתוב זה היה נראה מאוד
מבלבל, ומכיוון שיש לנו כ-10 וירג'ינים בצוות, כל בילבול קטן הופך אח"כ לכאב
ראש גדול.... :)  שוב תודה!!
