### ISSUE TITLE
בקשה לאפס סיסמא למשתמש ספארק

### ISSUE THREAD

**Issue by yossilan** [Midburn/spark#771]
אחד מחברי צוות המיצב שלי הינו "מאותגר-מחשבית", ואיכשהו הוא הצליח ליצור פרופיל ויש לו את הסיסמא הנכונה, אבל אי אפשר להתחבר לספארק עם הסיסמא הזו.... בשל זאת, אנחנו לא יכולים לצרף אותו למחנה שלנו מכיוון שהוא חייב להכנס לספארק כדי לאשר הצטרפותו (בניגוד למיצב ששם הוא לא היה צריך לאשר השתתפות).... 

שמו של המשתמש הוא גיא ולפיש
האימייל שלו (וגם שם המשתמש) הוא valfishguy@gmail.com 
המיצב המדובר הינו הדמיונון, מספר 295 בחלומות ו1999 בספארק.... 

במקום איפוס הסיסמא, הכי נוח יהיה אם הסיסמא של הפרופיל שלו פשוט תועתק לספארק וזהו...

**Comment by pandamichal** [comment]
היי יוסי,
כאן זה לא המקום לתמיכה טכנית.זוהי הפלטפורמה לפיתוח.
בבקשה שלח מייל לתמיכה 
support@midburn.org
