### ISSUE TITLE
Past Midburn events/sandbox -  shown to virgins

### ISSUE THREAD

**Issue by galnitsan** [Midburn/spark#774]
### Overview of the problem

Past Midburn events/sandbox -  shown to virgins

 This is about the Spark : Users module

 My **browser** is:  chrome
I am sure this issue is not duplicated - **not sure**

### Description

 Description of the bug, enhancement, or question 
Past Midburn events/sandbox -  shown to virgins

### Steps to Reproduce

1. login to Spark as a virgin user
2. Press the button of my midburn
3. see the names of midburn events
-->

### Expected behavior

to see only Midburn 2018

### Actual behavior

There are -
a. Midburn 2018
b. Midburn 2017
c. Sandbox 2017

![image](https://user-images.githubusercontent.com/20013504/37560510-48ded318-2a42-11e8-8792-bbc780c63fd6.png)

**Comment by amotenko** [comment]
@galnitsan , those entities do exist in the database, why don't you want the virgins to be able to see them?

**Comment by galnitsan** [comment]
Because I am a virgin and those entities are not relevant for me.

**Comment by amotenko** [comment]
this is not a bug, as discussed :)
