### ISSUE TITLE
A new request to join a camp will cancel out an existing authorized rquest

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#776]
TBD:
Exact steps to reproduce

**Comment by yaarams** [comment]
Flow one:

1. Camp manager adds a user
2. User approves participation in camp
3. User submits a request to participate in camp
4. Previous request is cancelled and user is not approved - again

Flow two:

1. User submits a request to participate in a camp
2. Camp manager approves user
3. Camp manager adds the user
4. Previous request is cancelled and user is not approved - again

**Comment by yaarams** [comment]
@amotenko seems like this issue is fixed already, we couldn't reproduce.
