### ISSUE TITLE
Query creation at metabase

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#777]
For theme camps tickets tracking they asked a query that should contain: 
For each camp:
-How many tickets allocation they got.
-How many they used (how many members they mark that should get a ticket)
-How many members of the camp that got ticket allocation actually bought the ticket.
In Hebrew:
עבור כל מחנה שקיבל הקצאת כרטיסים בספארק, רשימה של כמה כרטיסים הוקצו בפועל, וכמה נקנו

(לדוגמא: פוסינמה קיבלו מאיתנו 10 הקצאות, הקצו רק 7, קנו רק 3 - למשל)

**Comment by amotenko** [comment]
Just to clarify, queries are written in SQL, anybody with some SQL experience can take his

**Comment by OriHoch** [comment]
https://production.midburn.org/metabase/question/17

**Comment by pandamichal** [comment]
clerification:  
כל מחנה קיבל כמות מסויימת של הקצאות ויכל לסמן אנשים. . אז עמודה אחת של כמה הקצאות הוא קיבל. עמודה שנייה- כמה אנשים הוא סימן מתוך אותם ההקצאות.
מתוך האנשים שהוא סימן- כמה מהם קנו את הכרטיסים שלהם וכמה לא
הדבר היחיד שלא מוצג בספארק זה מי קנה בפועל את הכרטיס שהוקצאה לו.
![screenshot](https://user-images.githubusercontent.com/34742039/37652209-77a4b85e-2c43-11e8-97d1-ca83e3f54f23.png)

**Comment by pandamichal** [comment]
@OriHoch  what does it means that you removed your assignment? that it can't be done? Should I say to Adir? Can't we provide this query?

**Comment by OriHoch** [comment]
it means I'm not working on it at the moment, so it let's other people know the issue is available

I hope I'll get to it next week

**Comment by ghost** [comment]
Thanks @OriHoch!

Based on your query I added the missing column. 

Waiting for a review by whoever needs to review the report and I’ll close the issue.

**Comment by pandamichal** [comment]
Thank you guys! The query Elad completed with Ori , Helped us a lot!

**Comment by amotenko** [comment]
done
