### ISSUE TITLE
Spark signing in depends on profile update

### ISSUE THREAD

**Issue by pandamichal** [Midburn/spark#778]
If a user didn't sign in on the "terms and details" at the profile system (or didn't updated emergency contact) or any change needed - the user can't log into the spark.

The two systems don't need to be related in that manner.

**Comment by amotenko** [comment]
Agreed. I'm not going to say the obvious (that we are moving towards a new profile system that may or may not be a part of Spark etc.),
but,
to fix this right now, the change should be made on the side of Drupal since Drupal is failing the login attempt, not Spark.

**Comment by pandamichal** [comment]
OK, that's sad to hear.
So let's add please a notification on the Spark login screen (to prevent a lot of noise and tickets to support) that say: "failed to log in? Enter the Profile system and make sure you entered all the details". 
לא מצליחים להיכנס? כנסו למערכת הפרופילים ותוודאו שאין לכם פרטים נוספים למלא"
I'm expecting a lot of problems at the next sale (25/3).

**Comment by amotenko** [comment]
Agreed!
We do have such an issue, https://github.com/Midburn/spark/issues/578
I'll prioritize it

**Comment by amotenko** [comment]
it's better now
