### ISSUE TITLE
Ingestion of 2nd sale quotas

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#783]
I don't have the numbers yet but it might be a little different this time.
It is very important that the old data isn't thrown away.

We may receive the numbers in either one of two ways,
1. New valid absolute values (easy for us)
2. Just the deltas (a bit harder)

I'll update here, and let me know if you can take this.

**Comment by amotenko** [comment]
## Update

1. Data is in deltas but not from the total number of tickets allocated but rather actual number of tickets allocated. Sorry if confusing, let's talk and I'll explain

2. Old data should be set aside, new numbers inserted, and recombined after the sale.

3. Make sure to have a backup before running

**Comment by OriHoch** [comment]
confusing indeed, please describe what needs to be done.. otherwise, let's talk in the meeting Monday

**Comment by amotenko** [comment]
## Update Update

New data is better structured. The needed steps are:

1. Make sure we have a current backup
2. Overwrite old sale data with new sale data (similar to how we done it before)

**Comment by OriHoch** [comment]
@amotenko 
1. sent you the backup in slack
2. done on production

**Comment by amotenko** [comment]
## Update Update Update

Sent new and final data set received from camps department. This time it should be also the last time.

**Comment by amotenko** [comment]
Done on production.
