### ISSUE TITLE
File upload implementation to support docs & forms

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#79]
Camps need file uploading module, for documents (doc,xls,csv) mainly.

1. [x] need a bucket , key & secret. (update: we have the bucket named ``alex.spark``)
2. [ ] implement __[express-fileuploader-s3](https://www.npmjs.com/package/express-fileuploader-s3)__ package

**Comment by natekonimbo** [comment]
need a bucket , key & secret.

**Comment by OriHoch** [comment]
I can do that but need more details..

**Comment by asihud** [comment]
@OriHoch @mtr574 @natekonimbo @guywarburg 

For file upload:
1. On the edit camp http://localhost:3000/he/camps/1/edit we need to add another section:
    Files. (Current we have two tabs: Basic Information, Basic Details) , we will add File Upload 
2. On this section we will have various of File Types to upload.
    (Add on the camps/edit.jade one file option, we will add as much as we want)
3. Install the express-fileuploader-s3 to the node modules.
4. upon uploading files, we will use the uploaded files, and store them on the AWS-S3: https://www.npmjs.com/package/express-fileuploader-s3 (for a working example)
5. Saving the files/urls on the DB (still waiting to understand how we do that)
6. On the Manage Camps, at Documents & Forms, we will see a list (Grid Table) of all documents available, with camp and status of document (Can be filtered by camp, or status), and ability to change the status of the file.

Who has 3 hours to set this up ?
@guywarburg - i think you can set it in no time.

**Comment by OriHoch** [comment]
@asihud - great spec, but I think I'm missing something
could you please provide links / reproduction steps on the staging server?
currently if I go to: http://sparkstaging.midburn.org/he/camps/1/edit
It's stuck..

**Comment by asihud** [comment]
@OriHoch 
I am not working on the sparkstaging, so i do not know. maybe to ask alex or omer.
dont you have your own local copy ?

i am just asking @guywarburg to create all the front end first, 
and then i will update the spec accordingly.

**Comment by OriHoch** [comment]
@asihud  - it would be best to have issues reproducible on staging / test server
otherwise, it's hard to know what's the status of your local copy, which branch you are on, is it updated etc. etc...

**Comment by asihud** [comment]
the problem is that i do not have permission to merge to master, and not in charge of the staging.
and still dont know how to do that on github.. :)
I will ask on slak who in charge of that.

**Comment by OriHoch** [comment]
If the bug is reproduced on a specific branch then include that step in the reproduction steps...
But it would be better to work on master branch

**Comment by asihud** [comment]
@OriHoch 
Please update your branch with guy changes or even from asihud/Spark fork, to your branch.
It is include the file upload ui.
now need to implement it. please tell me that you are on this issue, and grabbed it.

**Comment by OriHoch** [comment]
@asihud  - you instructions are very ambiguous..
what is "guy changes"? what is "asihud/Spark fork" - a fork contains many branches
what is "my branch"? I don't have a single branch, I have a fork
it would be helpful to have full reproduction steps from start to finish

**Comment by asihud** [comment]
@OriHoch ,
sure. to sync:
1. go to PULL REQUEST , ask for NEW PULL REQUEST
2. on the Compare Changes page, press the compare across forks.
3. select for base fork: asihud/Spark base: master  to head fork (your fork)
4. sync changes.
5. implement the upload code.
6. we all happy!

**Comment by OriHoch** [comment]
@asihud  - I appreciate your work and trying to be clearer but the issue is still very confusing (to me..)
If you (AKA spark team / AKA midburn) would like to involve more volunteers in the project I believe you need to have clearer issues, requirements and working flow
However, I might be mistaken and maybe it's not needed and you will be able to have volunteers help you.. in that case, you are welcome to continue working as you (AKA spark team / AKA midburn) did before..
For me personally, it's very hard to work like this and I will probably be able to help less when the issues are not clear..

**Comment by asihud** [comment]
@OriHoch ,
No Problem. 
I will try to set up better spec.
Hope to see you tommorow at the meeting at iron source, so we can sync.

**Comment by ghost** [comment]
@asihud,
I’ll take this, as we discussed. 

I’ll hit you up on Slack if I have any Qs

**Comment by asihud** [comment]
@elad-lachmi ,
very good. I am assigning you once you will approve yourself as collaborator!
yeh, way to go!!!

**Comment by asihud** [comment]
@elad-lachmi 
Okay, to make it more usable:
- [ ] add a field on event array on the constants, that hold files upload for communities:
it should be like this:
    'MIDBURN2018': {
        bundles: [
            ticketType.SUPPORT_TICKET,
            ticketType.ADULT_TICKET,
            ticketType.CHILD_TICKET,
            ticketType.ADULT_DIRECT_SALE_TICKET,
            ticketType.YOUTH_TICKET,
            ticketType.LOW_INCOME_TICKET,
            ticketType.INTERNATIONAL_DIRECT_SALE
        ],
        files: {
            theme_camp: [
                {
                    id: 'safety_docs',
                    name_he: 'תיק בטיחות',
                    name_en: 'Safety Doc',
                    start_date: 0,
                    end_date: 0
                },
                {},
                {},
            ],
            art_installation: {

            },
            prod_dep: {

            }
        }
- [ ] On the file upload tab on edit camp page, we need to add the file upload option in the gui, (by the community group type), and to add a list of files
- [ ] Uploading file will upload it
- [ ] Display safe the file content with option to view/download it (after upload)

**Comment by ghost** [comment]
@asihud
Sounds good. 
Just another thing I think is worth implementing is the option to replace or delete a file, which has already been uploaded. 
The camp manager will be able to upload/delete/replace a file until the end date and an administrator can upload/delete/replace a file regardless of the end date.

**Comment by amotenko** [comment]
also done, I believe
