### ISSUE TITLE
Gate system filtering by event id

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#800]
At the moment the gate displays all tickets from all events, without regarding selected event id.

Add event ID to the query sent to the database when filtering tickets.

**Comment by yprez** [comment]
Looks like the tickets are already filtered by event id here:
https://github.com/Midburn/spark/blob/7eaacefc27a019bab6b8b794ce63e7e6a36dc9db/routes/pages/gate_routes.js#L40

Am I missing something?

**Comment by yprez** [comment]
Found the problem I think- the order of the AND/OR conditionals were wrong, andWhere should come first.

**Comment by amotenko** [comment]
In addition to the excellent work done here there seem to be another root cause

https://github.com/Midburn/spark/issues/808

**Comment by Aroundafur** [comment]
@amotenko I reviewed this with @NitayRabi  and we didn't find a bug. Query works as expected and info is properly shown. @NitayRabi will add ticket creation to seed.
