### ISSUE TITLE
Some tickets are associated with wrong event id

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#808]
Example:

ticket id `46348` is from 2017 Sandbox, associated with Midburn 2018 

Env:

Production  and staging

This is bad because it displays noisy data when filtering in the Gate system.

**Comment by amotenko** [comment]
those are probably the 3752 users that are 'in' the event.

**Comment by ArtyomKa** [comment]
Didn't Elad solve this? (I can't tag him via email).

**Comment by amotenko** [comment]
I don't know if those are new tickets that were synced incorrectly (probably not new, as those are sandbox 2017 tickets), or was it lying around in our database before and we didn't notice.

**Comment by OriHoch** [comment]
If you want to query the profiles DB directly, here is a query which returns tickets - 
https://production.midburn.org/metabase/question/23

**Comment by amotenko** [comment]
Not sure how but at the moment those tickets have the right event id, closing.

**Comment by amotenko** [comment]
Those tickets do have the wrong event id association on staging database
