### ISSUE TITLE
Some art installations from 2017 appear in the 2018 filtering

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#809]
Those are that on top (production, staging ids):

2104, 2101, 2103, 2102

1. Are those camps really from 2017
2. Why do they appear in 2018 event filtering

**Comment by amotenko** [comment]
All those also appear as 'CAMP' in type in `user_groups`, that is not even a valid value?

**Comment by amotenko** [comment]
Also related, all *camps* in the 2018 filtering, likewise, have 2017 event id association in user_groups, and have the type 'CAMP', which I believe is not a valid value (please correct me).

**Comment by OriHoch** [comment]
you are correct, the data in `users_groups` and `users_groups_memberships` is invalid - just ignore it

the correct data is in `camps` and `camp_members`

**Comment by OriHoch** [comment]
the data in users_groups table is inserted by a trigger which is hard-coded to 2017 CAMP

I don't know why we have this trigger, all data is in camps and camp_members

**Comment by amotenko** [comment]
when looking at camps table, data seem to be in order
