### ISSUE TITLE
In user_group table, type should be an enum

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#810]
not a varchar, that is just ridiculous.

Depends on #809 ! 
Data is corrupted at the moment so don't migrate.

**Comment by OriHoch** [comment]
I think we should remove the users_groups and users_groups_membership tables - I don't see why they are needed

replace all occurences to use camps and camp_members

**Comment by amotenko** [comment]
Good! @OriHoch  can I count on you with this delicate procedure?

**Comment by OriHoch** [comment]
I'll have a look next week

**Comment by amotenko** [comment]
user_group used by gate module, won't be fixed this year.
but also no need to waste time on maintenance
