### ISSUE TITLE
Camps Migration

### ISSUE THREAD

**Issue by netanelben** [Midburn/spark#82]
Migration for model: camp

add these columns:

- accept_families (boolean)
- facebook_page_url (text)
- contact_person_id (a constraint of model: user)
  each camp has contact person, his details (name, email) published in the website later.

fix here: https://github.com/Midburn/Spark/pull/84

**Comment by OriHoch** [comment]
@mtr574 - how is "contact_person_id" field different then the existing "main_contact" field?

**Comment by natekonimbo** [comment]
@OriHoch ``main_contact`` can be camp owner/manager unlike ``contact_person`` who is the person you contact if you'd like to join the camp, for example, and his details will be published to the website.

**Comment by OriHoch** [comment]
cool, then issue is done once #84 is merged
