### ISSUE TITLE
Camps: Remove member doesn't work

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#820]
On staging, as admin, go to Campy McCampface, try to remove one of the fake users

**Comment by Aroundafur** [comment]
SweetAlert: Unexpected 2nd argument (() => {
 var request_str = `/camps/${camp_id}/members/${user_id}/${action_type}`
 $http.get(request_str).then((res) => {
 sweetAlert(tpl.alert_success_1, tpl.alert_success_1, "success");
 $scope.getCamps(camp_id);
 }).catch((err) => {
 jsonError=err.data.data.message;
 sweetAlert("Error!", "Something went wrong, please try again later \n" + jsonError, "error");
 })
 })

member.user_id is the second argument.

**Comment by NitayRabi** [comment]
Hey, - https://github.com/Midburn/spark/pull/821 fix it.

**Comment by amotenko** [comment]
fixed
