### ISSUE TITLE
[SUPPLIERS] - Entry management joins on missing table

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#831]
Error when going to suppliers entry management screen
Wrong name?
Missing migration?

> ```select * from `suppliers_gate_entrance_info` inner join `suppliers` on `suppliers_gate_entrance_info`.`supplier_id` = `suppliers`.`supplier_id` where `suppliers_gate_entrance_info`.`supplier_status` = 'Inside' and `suppliers_gate_entrance_info`.`event_id` = 'MIDBURN2018' - ER_NO_SUCH_TABLE: Table 'spark.suppliers_gate_entrance_info' doesn't exist```

**Comment by NitayRabi** [comment]
#836 - should fix the issue

**Comment by amotenko** [comment]
fixed
