### ISSUE TITLE
[SUPPLIERS] - minor issue dump

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#832]
To avoid clutter I"m batching some suppliers stuff here, feel free to address items partially.

- [x] Phone stored as integer (truncates leading zero)
- [x] Last updated - not sure if needed, if needed not sure if should be displayed, if displayed consider a more human readable format
- [x] When adding camp to supplier, camp is chosen from a drop-down. This is a not very good ux to say the least, consider using a text field with autocomplete.
- [x] I know it was merged but I think file upload is missing from the wizard?
- [x] Also I know it was addressed but pizza feature is also missing at the moment
- [x] Barcode generation and download, also need to talk to app guys about it

**Comment by NitayRabi** [comment]
#839 - Fixs last update, and camp dropdown

**Comment by noamr** [comment]
Adding supplier choice to camps

**Comment by amotenko** [comment]
Continuation to file upload
https://github.com/Midburn/spark/issues/898

**Comment by amotenko** [comment]
done
