### ISSUE TITLE
suppliers-admin: Sort default by name and add sort-arrows to the chart headers [Bug] [Javascript]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#847]
The Problem:
As am Admin user, When visiting suppliers-admin page, I would like the chart to be sorted default by name and to add sort-arrows to the chart headers

Steps:
1. Login as ad admin.
https://spark.staging.midburn.org
2 Go to suppliers-admin page
https://spark.staging.midburn.org/he/suppliers-admin

Result:
not sure how the chart is sorted, and the user dont know he can click on headers to sort by them. (See screenshot)

Expected:
Chart to be sorted default by name
and to add sort-arrows to the chart headers

![image](https://user-images.githubusercontent.com/13450170/38736331-5d95134c-3f34-11e8-9ac2-fb6eb1640b10.png)

**Comment by NitayRabi** [comment]
#853

**Comment by amotenko** [comment]
done
