### ISSUE TITLE
suppliers: Change copy on buttons [Bug] [Javascript]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#854]
Change copy on buttons:
'הזנת ספק למערכת'
'הכנסת ספק לתוך העיר'

url:

https://spark.staging.midburn.org/he/gate/suppliers

![image](https://user-images.githubusercontent.com/13450170/38741130-e12c2896-3f41-11e8-9573-ccc791966bb9.png)

**Comment by NitayRabi** [comment]
#855

**Comment by amotenko** [comment]
done I guess, although I don't see any problem with the original labels.
