### ISSUE TITLE
supplier: When creating/editing a supplier, please Add more options [Bug]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#865]
When creating/editing a supplier, please Add more options:
 - הובלה 
 - ספקים קבועים
 - ספקים זמניים
- אחר

Note:
also in En

![image](https://user-images.githubusercontent.com/13450170/38748708-ab8ba00c-3f57-11e8-88a4-d4dd0c913c8b.png)

**Comment by benmarder** [comment]
#890

**Comment by amotenko** [comment]
Sorry bros, this is actually not the desired behavior.
Please see here:
https://github.com/Midburn/spark/issues/899
