### ISSUE TITLE
Suppliers: Entering a new supplier with very long ID number, we cant save [Bug]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#869]
Suppliers: Entering a new supplier with very long ID number, we cant save 
Steps:
create a new supplier
https://spark.staging.midburn.org/he/suppliers/new?c=1234567890123456789

Expected:
1. make sure users will not get this error in console
2. Please make sure the supplier ID will be limited to 9 numbers only.

Note:
Getting error in console:
jquery.min.js:4 POST https://spark.staging.midburn.org/suppliers/new 500 ()
send @ jquery.min.js:4
ajax @ jquery.min.js:4
_sendSuppliersRequest @ suppliers.js:204
(anonymous) @ suppliers.js:184
dispatch @ jquery.min.js:3
r.handle @ jquery.min.js:3

![image](https://user-images.githubusercontent.com/13450170/38752250-311a13ce-3f63-11e8-97b6-bfc8d4b5cf04.png)

**Comment by hila211** [comment]
ID and company number are up to 9 digits.

**Comment by benmarder** [comment]
#890

**Comment by amotenko** [comment]
done
