### ISSUE TITLE
Suppliers: As a Camp manager I would like the option to add Suppliers to my camp

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#870]
As a Camp manager I would like the option to add Suppliers to my camp
This option is not availble
url:
https://spark.staging.midburn.org/he/camps/2045/edit

![image](https://user-images.githubusercontent.com/13450170/38752544-3f7c659c-3f64-11e8-86b7-2cd737208c2a.png)

**Comment by amotenko** [comment]
done! new functionality available from this screen
