### ISSUE TITLE
Suppliers: Clicking 'add' leave the user on the same page Need to lead him back to suppliers [Bug]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#871]
Clicking 'add' leave the user on the same page
Need to lead him back to suppliers

URL:
https://spark.staging.midburn.org/he/gate/suppliers

![image](https://user-images.githubusercontent.com/13450170/38753019-bff83e8e-3f65-11e8-9ea6-e788545b516b.png)

**Comment by NitayRabi** [comment]
#879

**Comment by amotenko** [comment]
done
