### ISSUE TITLE
Suppliers: Remove 'add new supplier' button from gater page [Bug]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#874]
Remove 'add new supplier' button from gater page
https://spark.staging.midburn.org/he/gate/suppliers

(The gater needs another page, and the location is wrong, there will be another solution in another ticket )

![image](https://user-images.githubusercontent.com/13450170/38825324-de926aa8-41b4-11e8-8215-88fc0c6bc770.png)

**Comment by NitayRabi** [comment]
#878

**Comment by amotenko** [comment]
done
