### ISSUE TITLE
Suppliers: Add a new page 'Create new supplier + belongs to camp + enter to the city' [Feature]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#875]
As a Gatter, When I'm in the event and I have a supplier that I have to let in, I would like to have a One page that will create-match-enter the supplier to the city.

Please create a new page that will have have 3 functions in one,
1. Add a supplier to the db
2. match the new supplier to a camp
3. enter the supplier to the city

In the end of the page, after clicking 'save' will popup a window with a msg that will warn the gatter that he is about to let the supplier to enter to the city in red
(In Red: אנא שים לב, הינכם עומדים להכניס ספק לתוך העיר)

A link to this page will be in a button name 'צור ספק חדש'
location of the button will be in the bottom of the Gatter-supplier page, see screenshot
https://spark.staging.midburn.org/he/gate/suppliers

Roles: Only 'Admin' and 'Gater' roles will have access to this page

![image](https://user-images.githubusercontent.com/13450170/38826242-e49f393c-41b7-11e8-8a32-cb6b9ca4bd7f.png)

**Comment by amotenko** [comment]
This should be (in theory) a rare flow.
Most (all) suppliers should be created and assigned before the event, since they have the whole thing with the contract they need to sign and all.

Though if needed, this functionality is available.
