### ISSUE TITLE
User with role 'gate_manager' should have access to gate entrance and supplier entrance [Bug] 

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#885]
## reproduction steps
* log-in with user which have `gate_manager` role

#### expected
* should have access to gate entrance management
* URL1: 
  * https://spark.staging.midburn.org/he/gate
* URL2:
  * https://spark.staging.midburn.org/he/gate/suppliers

#### actual
* no access to gate entrance management

![image](https://user-images.githubusercontent.com/13450170/38833495-5eb6c5ee-41ce-11e8-842e-31dddb93c3e6.png)

**Comment by amotenko** [comment]
correction, actual role is gate_admin

**Comment by amotenko** [comment]
Sorry! My bad, role is indeed `gate_manager`

From what I see gate_manager has access to the relevant views, can see tickets, but can't see suppliers (probably because of endpoint)

I'm closing this issues and opening the following:
https://github.com/Midburn/spark/issues/901

**Comment by amotenko** [comment]
Also
https://github.com/Midburn/spark/issues/903
