### ISSUE TITLE
Event admin should be able to switch event from early arrival to regular arrival

### ISSUE THREAD

**Issue by amotenko** [Midburn/spark#906]
Event admin panel should contain a switch that turns early arrival mode on and off.
This should affect the logic in the ticketing endpoint.

I assume there is some support for this from last year but it's probably not compatible with our new data model.

**Comment by ArtyomKa** [comment]
What is the use case exactly? Like when early arrival phase ends, and the
event is open?

**Comment by amotenko** [comment]
Yes, exactly.
We cannot know in advance when this magic time _t_ happens because it depends on the authorities.

**Comment by ArtyomKa** [comment]
Fixed by #912

**Comment by amotenko** [comment]
done
