### ISSUE TITLE
Approved user trying to get out of the camp getting 404 [Bug]

### ISSUE THREAD

**Issue by ozsoffy** [Midburn/spark#913]
Approved user trying to get out of the camp getting 404

![image](https://user-images.githubusercontent.com/13450170/39149898-45dc59d2-4749-11e8-8505-ac907824e930.png)

**Comment by yprez** [comment]
Not very critical by itself, but annoyingly blocks checking other camp membership bugs

**Comment by yprez** [comment]
Nope!
actually looks like the same bug as #886

**Comment by yprez** [comment]
Works on staging.
