### ISSUE TITLE
Publish camps index page

### ISSUE THREAD

**Issue by natekonimbo** [Midburn/spark#97]
This issue has two-steps:

1. Insert camps data from Google forms (DevOps - Nitay should help me)
Lilach started to collect camps data with Google forms, so she has a Doc format with all the current data. Technically it has to be store in Spark's database, mind to adapt the table column names.

 - Contact Lilach Givaty to get the data.
 - The data will be used in Camps Index page (in Midburn.org)

2. Serving camps_index page (Front-end)
Need to serve the static web-page from this repo: https://github.com/Midburn/camps_index
in ``oldsite.midburn.org`` - at first, later will be published in ``midburn.org``

**Comment by natekonimbo** [comment]
i got them

**Comment by netanelben** [comment]
Done.
https://midburn-camps.firebaseapp.com/
