### ISSUE TITLE
Fix Cross-Origin issue for Camps-Index-API

### ISSUE THREAD

**Issue by guywarburg** [Midburn/spark#98]

**Comment by guywarburg** [comment]
![screen shot 2017-02-05 at 1 21 20 pm](https://cloud.githubusercontent.com/assets/24923164/22626487/3ea5dd30-ebb7-11e6-90db-289131496031.png)
*Error when trying to call api

**Comment by netanelben** [comment]
Not an issue yet,
Need to implement JSONP.
