### ISSUE TITLE
[Camp Editing] Camp description box should fit text.

### ISSUE THREAD

**Issue by NitayRabi** [Midburn/spark#987]
### Overview of the problem
Camp description (in camp editing section) doesn't fit text and is un-scroll-able.

### Steps to Reproduce
1. Navigate to camp editing
2. View description area
### Expected behavior
Text box should be larger and scroll-able
### Actual behavior
Text is unreadable and not scroll-able.

![image](https://user-images.githubusercontent.com/24541325/49434845-db9a4400-f7bd-11e8-8909-72d403260e60.png)

**Comment by Michal-Leizerowitz** [comment]
Same exact issue when editing a supplier page (comment box):
![image](https://user-images.githubusercontent.com/38831553/49795090-cbe0a980-fd41-11e8-87a5-9ca4b9a5ab40.png)

**Comment by NitayRabi** [comment]
Fixed via #996
