### ISSUE TITLE
[Camp Editing] Remove # (id) column from members editing

### ISSUE THREAD

**Issue by NitayRabi** [Midburn/spark#990]
### Overview of the problem
Remove `#` Column from Edit members view under camp editing
![image](https://user-images.githubusercontent.com/24541325/49442211-75b7b780-f7d1-11e8-81b8-769069275716.png)

**Comment by dani0197** [comment]
@NitayRabi  I think i did it! 
ill make a PR so you could check it.

**Comment by NitayRabi** [comment]
Fixed by #993
